examples/plot_sin_black_background.py
in order to show the impact of commit d5a5507cd9d4b2ba4af0bf4cf42bbda043853cb5.
Maybe the matplotlib example can be simplified but it does the job...
For completeness, here how the the saved image looks like:
=> Add plot with black background in examples

examples/plot_grow.py, sphinxgallery/_static/gallery.css, sphinxgallery/_static/gallery.scss, sphinxgallery/gen_rst.py
Including a cleaner css file with the sphx-glr prefix for all item used in sphinx-gallery.
=> Update into a unified sphinx-gallery namespace

bin/copy_sphinxgallery.sh, doc/advanced_configuration.rst, setup.py
This script is designed for updating sphinx-gallery in third party
packages. Performs a download from PyPI.
=> Shell script for the local embeding

sphinx_gallery/_static/gallery.css, sphinx_gallery/gen_rst.py, tutorials/plot_notebook.py
=> STYLE: change the color of the output of a script

README.rst, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_gen_rst.py
In response to #64 this change follows the code md5
=> [MRG+1] Check script update by md5 updates

doc/advanced_configuration.rst, sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_gen_rst.py
closes https://github.com/sphinx-gallery/sphinx-gallery/issues/82
=> [MRG+1] execute only examples matching specified pattern

CHANGES.rst, sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py
cc @jaeilepp 
that's useful in mne-python to tracking the examples that take the most time.
@Titan-C feel free to take over to make it at your taste
=> plot sorted running time of examples when building the doc

doc/advanced_configuration.rst
cc @GaelVaroquaux as we discussed yesterday
=> Minor tweaks to regexp matching doc

doc/conf.py
=> MRG: Fix exception

sphinx_gallery/_static/gallery.css, sphinx_gallery/notebook.py
This is a very minor pull request, but it includes a few typos or improvements that were reported by the ``scikit-image`` folks in https://github.com/scikit-image/scikit-image/pull/2078 (since we're including sphinx-gallery files -- at least until the next release). 
Since I made the changes for our version, I thought I might as well submit the changes as a PR.
=> A couple of typos / improvements

README.rst
See http://scikit-image.org/docs/dev/auto_examples/ ! :-)
=> [MRG+1] Added scikit-image to list of projects

setup.py
This should fix #123 and close #124 
@jforbess is this working for you?
=> UTF-8 in setup.py

sphinx_gallery/gen_rst.py
=> stdout info on file build and time

sphinx_gallery/_static/gallery.css, sphinx_gallery/docs_resolv.py
=> CSS: fix tooltip

CHANGES.rst, sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py
This are simple fixes to issues #164 and #165
=> Fix readme bugs

circle.yml
This produces artifacts like:
https://13-39034777-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/doc/_build/html/index.html
Just 1) needs to be enabled by an admin on CircleCI, and 2) turn on permissive builds for PRs (probably).
=> ENH: Add CircleCI

README.rst
=> README states that dependencies are on the user's responsibility

README.rst
Thanks for the awesome project!
=> Add SunPy to projects using sphinx-gallery

sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/conftest.py, sphinx_gallery/tests/test_gen_rst.py
I had some ASCII encode/decode errors without this. I can try to come up with a test if necessary but it might take some time.
=> [MRG+1]: Use unicode

sphinx_gallery/backreferences.py
Fix #253
Another attempt of #254
Also see astropy/sphinx-automodapi#29
=> Enforce UTF8 encoding in backreferences

sphinx_gallery/docs_resolv.py
=> Correctly re-raise errors in doc resolver.

doc/advanced_configuration.rst, doc/conf.py
Update so that the backref point to the latest numpy, and not numpy 1.9.1.
=> [MAINT] Update link to numpy to point to latest

CHANGES.rst, doc/advanced_configuration.rst, sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py
=> Add threshold below which computation time is not reported.

CHANGES.rst, doc/advanced_configuration.rst
I put this in 1.12 but let me know if it should go in `git master`
Closes #302
=> FIX: Update docs

circle.yml
Let's see if CircleCI is happy with this.
=> [MRG+1] FIX: Update packages

doc/conf.py
=> fix binder doc configuration

sphinx_gallery/binder.py
=> https badge

CHANGES.rst, sphinx_gallery/_static/gallery.css, sphinx_gallery/downloads.py
To make them more visible to users for download
=> [MRG] CSS: float the download buttons on wide screens

sphinx_gallery/_static/gallery.css
Fix a bug in my previous layout (minor one, but this fix reduces screen
real estate used by download buttons).
=> [MRG]: MISC: CSS: fix predecence

sphinx_gallery/_static/gallery.css, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_gen_rst.py
=> Gallery output images have own css class

sphinx_gallery/tests/test_gen_gallery.py
The nightly cron job failed, this is a quick workaround so we can stay green.
=> FIX: Workaround for temp Sphinx 1.8.0 bug

.circleci/config.yml
Use checkout in the deploy step.
=> [MRG] Fix Circle v2

.gitignore, sphinx_gallery/tests/test_full.py, sphinx_gallery/tests/test_gen_gallery.py
Better fix than #387. Passes on my machine™
=> MRG: Fix for 1.8.0 dev

.circleci/config.yml, appveyor.yml, continuous_integration/travis/install.sh, doc/conf.py, doc/configuration.rst, requirements.txt, sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_full.py, sphinx_gallery/tests/test_gen_rst.py, sphinx_gallery/tests/tinybuild/conf.py
This PR:
- Rebased #374 
- fixed a sneaky problem where `memory_profiler.memory_usage` could end up calling a given function more than once (!)
- added docs for `show_memory`
- adds `memory_profiler` to `.circleci`
- modifies the call to use a "memory delta" rather than the total memory (which could accumulate due to running)
Ready for review/merge from my end. @GaelVaroquaux you had the most recent comment on this.
@tamasgal do you want to see if it works for you?
=> ENH: Profile memory

doc/conf.py, doc/configuration.rst, sphinx_gallery/gen_gallery.py, sphinx_gallery/tests/test_full.py
=> MRG: Add timing information

sphinx_gallery/tests/test_gen_gallery.py
Fixes things locally after reproducing the error with sphinx-dev that we have gotten [recently on Travis](https://travis-ci.org/sphinx-gallery/sphinx-gallery/jobs/463698115#L1174). See for explanation:
https://github.com/sphinx-doc/sphinx/pull/5718#issuecomment-444739024
=> FIX: Fix for latest sphinx-dev

.circleci/config.yml, .travis.yml, README.rst, continuous_integration/travis/install.sh, continuous_integration/travis/test_script.sh, requirements.txt, setup.py, sphinx_gallery/tests/test_full.py, sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py
=> MAINT: Modernize requirements

.circleci/config.yml, CHANGES.rst, doc/conf.py, doc/configuration.rst, setup.cfg, sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_full.py, sphinx_gallery/tests/tinybuild/conf.py
I thought this might be a useful feature, let's see if it actually works.
=> [MRG+1]: Output JUnit XML file

.travis.yml, continuous_integration/travis/test_script.sh, setup.cfg, sphinx_gallery/py_source_parser.py, sphinx_gallery/tests/test_py_source_parser.py
This gets `sphinx-gallery` working locally on 3.8.alpha2 for me.
Closes #442
=> MRG: Adjust lineno for 3.8

CHANGES.rst, sphinx_gallery/__init__.py
prepping the changelog and version for a release. Once somebody gives me the thumbs up, I will do:
1. Merge this into Master
2. Upload Master to pypi as v0.3.0
3. Add a new release to the tags for this repo
4. Bump version number to v0.3.1.dev0 and self-merge that one
Sounds good? I'll wait for somebody to approve or merge this before continuing!
=> Release v0.3.0

MANIFEST.in
Solves the sdist problem with v0.3.0 (see #406)
=> [MRG+1] Add requirements.txt to manifest

.circleci/config.yml, README.rst, doc/advanced.rst, doc/conf.py, doc/maintainers.rst, sphinx_gallery/backreferences.py, sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py, sphinx_gallery/scrapers.py, sphinx_gallery/tests/test_backreferences.py, sphinx_gallery/tests/test_full.py, sphinx_gallery/tests/test_scrapers.py, sphinx_gallery/tests/tinybuild/conf.py, sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py, sphinx_gallery/tests/tinybuild/examples/plot_svg.py
=> MRG: Add SVG support

sphinx_gallery/binder.py
=> FIX: allow Dockerfile

README.rst
=> Mention pytest-coverage dependency

sphinx_gallery/tests/test_full.py
Works around windows mtime being an iffy test for us.
=> MAINT: Tolerate Windows mtime

doc/configuration.rst
=> Add list of external image scrapers

README.rst
=> Add PlasmaPy to list of sphinx-gallery users

.gitignore, CHANGES.rst, doc/maintainers.rst
Updates docs with major changes and mentions #405 and #407. Also tweaks the release docs to streamline things a bit.
@choldgraf feel free to merge if you're happy.
=> ENH: Update docs

sphinx_gallery/backreferences.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_backreferences.py
Closes #497.
@drammock can you review and see if this fixes the problem for you? Locally for me it fixes the issue you posted about.
=> ENH: Remove some Sphinx markup from text

CHANGES.rst, doc/maintainers.rst, setup.py, sphinx_gallery/__init__.py
@choldgraf last one before I push to PyPi.
=> MAINT: Bump version for release

README.rst
Thank you for this nice package!
=> Add FURY to the sphinx-gallery users list

setup.cfg
Hopefully fixes https://travis-ci.org/sphinx-gallery/sphinx-gallery/jobs/552653234
=> MAINT: Fixes for latest pytest

doc/getting_started.rst
I've made some changes to the 'getting started' page to make it make it more friendly for new users and more cohesive.
Happy to amend if anything is incorrect/misleading or if too much detail.
=> Improve documentation

sphinx_gallery/gen_rst.py
=> look for both 'README' and 'readme'

doc/advanced.rst, doc/getting_started.rst
closes #472 
Hope this is what you were after @choldgraf
=> [MRG] DOC: Explain image scraper inputs

doc/syntax.rst, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_gen_rst.py
closes #517 
Includes test and update to doc. (sorry for typo in commit message)
=> [MRG] Allow punctuation marks in title

sphinx_gallery/gen_rst.py
A shot in the dark to try to fix https://bugs.python.org/issue35894 / https://travis-ci.org/sphinx-gallery/sphinx-gallery/jobs/593633009
=> MAINT: Fix for 3.8

doc/getting_started.rst, doc/syntax.rst
I noticed some typos/formatting mistakes from when I did #533.
=> [MRG] DOC typos and clarifications

README.rst, doc/index.rst, doc/projects_list.rst
=> list of projects using sphinx-gallery

sphinx_gallery/py_source_parser.py, sphinx_gallery/tests/test_gen_rst.py
=> [MRG] Fix terminal rst block last word 

doc/configuration.rst
=> [MRG] DOC: Add warning filter note in doc

sphinx_gallery/gen_gallery.py, sphinx_gallery/tests/test_gen_gallery.py
=> [MRG] Check backreferences_dir config

sphinx_gallery/gen_gallery.py, sphinx_gallery/tests/test_gen_gallery.py
=> [MRG] Add ignore pattern to check dups

appveyor.yml
Let's see if this fixes the AppVeyor problem
=> MAINT: Bump AppVeyor to 3.7

doc/advanced.rst
Just a quick follow-up to #582 to fix the language of the code block.
=> DOC: Fix code block language

examples/plot_6_function_identifier.py, sphinx_gallery/backreferences.py, sphinx_gallery/docs_resolv.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_backreferences.py, sphinx_gallery/tests/test_full.py, sphinx_gallery/tests/tinybuild/examples/future/README.rst, sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py
Also a tiny fix for a short-circuit in `SphinxDocLinkResolver.resolve`.
=> MRG, FIX: Link to RandomState properly

doc/configuration.rst
Minor clarifications because I was a bit confused when re-reading the doc. Suggestions/changes welcome.
=> [DOC] Minor amendments to CSS config part

.circleci/config.yml, .travis.yml, README.rst, continuous_integration/travis/install.sh, dev-requirements.txt, doc/binder/requirements.txt, doc/conf.py, doc/index.rst, requirements.txt, setup.py, sphinx_gallery/gen_gallery.py, sphinx_gallery/scrapers.py, sphinx_gallery/tests/conftest.py, sphinx_gallery/tests/test_docs_resolv.py, sphinx_gallery/tests/test_full.py, sphinx_gallery/tests/test_gen_gallery.py, sphinx_gallery/tests/test_gen_rst.py, sphinx_gallery/tests/test_scrapers.py, sphinx_gallery/tests/tinybuild/conf.py, sphinx_gallery/tests/tinybuild/examples/local_module.py, sphinx_gallery/utils.py
=> MRG, MAINT: Update deps

sphinx_gallery/_static/gallery-binder.css, sphinx_gallery/_static/gallery-dataframe.css, sphinx_gallery/_static/gallery.css, sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/conftest.py, sphinx_gallery/tests/test_gen_gallery.py
Implements ideas from https://github.com/sphinx-gallery/sphinx-gallery/issues/317#issuecomment-575719139.
If we decide to go this route (which seems like a useful refactoring) then I can add config instructions.
=> MRG, MAINT: Split CSS and add control

doc/syntax.rst, sphinx_gallery/tests/reference_parse.txt, tutorials/plot_parse.py
=> recommend consistent use of one block splitter

doc/getting_started.rst, doc/syntax.rst, sphinx_gallery/tests/reference_parse.txt, tutorials/plot_parse.py
=> [MRG+1] DOC Improve doc of splitters and use in IDE

sphinx_gallery/tests/test_full.py
=> BUG Fix test for new sphinx

doc/advanced.rst
=> DOC capture repr in scraper section

sphinx_gallery/downloads.py, sphinx_gallery/tests/test_full.py, sphinx_gallery/tests/test_gen_rst.py
=> ENH: Add sub-classes for download links

doc/configuration.rst, sphinx_gallery/gen_gallery.py, sphinx_gallery/notebook.py, sphinx_gallery/tests/test_gen_gallery.py, sphinx_gallery/tests/test_notebook.py
=> ENH Add last cell config

sphinx_gallery/gen_gallery.py, sphinx_gallery/notebook.py
Related to https://github.com/sphinx-gallery/sphinx-gallery/pull/625#issuecomment-601180458
Remove redundancy as default config set and (possible) circular logic in `_complete_gallery_conf`
=> MRG Remove last/first_notebook_cell redundancy

doc/syntax.rst, examples/no_output/plot_raise.py, examples/plot_1_exp.py, examples/plot_3_capture_repr.py, examples/plot_4b_provide_thumbnail.py, examples/plot_5_unicode_everywhere.py, examples/plot_6_function_identifier.py, sphinx_gallery/tests/reference_parse.txt, tutorials/plot_parse.py
closes #620 
Have replaced lines of `#`'s with `# %%` where ever possible. Minor update on `plot_parse` for clarity.
ping @GaelVaroquaux
=> DOC use # %%

CHANGES.rst, sphinx_gallery/__init__.py
=> Release 0.6.0

sphinx_gallery/__init__.py
Sorry, @larsoner, another question - in the [maintainers](https://sphinx-gallery.github.io/dev/maintainers.html#how-to-make-a-release) doc under 'create a new release on github', I didn't understand what:
```
Make sure to update any links to point to the tag that will be created for this release 
(e.g., change HEAD to v0.3.0).
``` 
was referring to? This link?
```
[Full Changelog](https://github.com/sphinx-gallery/sphinx-gallery/compare/v0.5.0...v0.6.0)
```
=> Bump release version

sphinx_gallery/gen_gallery.py
Currently the error render as "... of typestr or None..."
=> Fix missing space in error message.

sphinx_gallery/gen_gallery.py, sphinx_gallery/tests/test_gen_gallery.py
closes #440 
Not a fan of spaces in filenames so I think the warning is adequate.
=> BUG Checks if filenames have space

CHANGES.rst, sphinx_gallery/__init__.py
=> Release 0.6.1 for Zenodo

doc/maintainers.rst
I feel the need to amend this every time I use it, sorry!
=> DOC Amend maintainers

doc/conf.py
=> Update pandas intersphinx url

doc/configuration.rst, doc/getting_started.rst
Fixes some typos and clarifies some areas.
=> DOC Fix typos, clarify

doc/configuration.rst
=> DOC Note config comment removal in code only

sphinx_gallery/backreferences.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_backreferences.py, sphinx_gallery/tests/test_full.py
=> ENH Add alt attribute for thumbnails

examples/plot_0_sin.py
Master is failing with this warning:
```
sphinx_gallery/tests/test_notebook.py::test_file_is_generated
<unknown>:51: DeprecationWarning: invalid escape sequence \s
```
Hopefully this fixes it.
=> DOC Update label to raw string in plot_0_sin.py

doc/configuration.rst, sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/conftest.py, sphinx_gallery/tests/test_gen_gallery.py
Closes #671.
@pmeier can you see if this works for your use case?
=> ENH: Add show_memory extension API

sphinx_gallery/tests/test_full.py
=> Fix regex for numpy RandomState in test_full

appveyor.yml, doc/_static/theme_override.css, doc/conf.py, doc/configuration.rst, examples/plot_8_animations.py, sphinx_gallery/_static/gallery.css, sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py, sphinx_gallery/scrapers.py, sphinx_gallery/tests/test_full.py, sphinx_gallery/tests/tinybuild/conf.py, sphinx_gallery/tests/tinybuild/examples/plot_animation.py, sphinx_gallery/utils.py
Closes #150.
@choldgraf @lucyleeow do you want to take a first look at these? Once you're happy I'll ping the folks from #150 to take a look. (Anyone else can feel free to comment as well, just don't want to spam everyone if this is still half-baked/experimental!) But at least it seems to work [for MNE-Python](https://github.com/mne-tools/mne-python/pull/7783):
- [examples page](https://20084-1301584-gh.circle-artifacts.com/0/dev/auto_examples/index.html#visualization)
- [the example](https://20084-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_evoked_topomap.html#animating-the-topomap)
They both show animations when built with this branch.
=> ENH: Add support for FuncAnimation

continuous_integration/travis/install.sh
Hopefully fixes https://travis-ci.org/github/sphinx-gallery/sphinx-gallery/jobs/697655504
=> MAINT: Bump pytest versions in Travis runs

.circleci/config.yml, continuous_integration/travis/install.sh, doc/configuration.rst, sphinx_gallery/gen_gallery.py, sphinx_gallery/notebook.py, sphinx_gallery/tests/test_full.py, sphinx_gallery/tests/test_gen_gallery.py, sphinx_gallery/tests/test_notebook.py, sphinx_gallery/tests/tinybuild/conf.py, sphinx_gallery/utils.py
closes #219
Use pypandoc (https://github.com/bebraw/pypandoc), if available, to convert rst to md for ipynbs.
Considerations:
* Should we add a configuration option for this to allow users to set pandoc arguments or filters? Not sure how often these are used. The downside is that some settings may break our ipynb conversion.
Todo:
Will add a test in `test_full.py`
=> ENH Support pypandoc to convert rst to md for ipynb

doc/advanced.rst, doc/faq.rst, doc/syntax.rst
Related to #725 
Also amended some doc nitpicks.
=> DOC add section on interpreting error/warnings

doc/configuration.rst
Expand doc on `sphinx_gallery_thumbnail_path`
=> DOC Expand on sphinx_gallery_thumbnail_path

sphinx_gallery/tests/test_notebook.py
@lucyleeow feel free to merge if you're happy with this solution
=> FIX: Restore whitespace

sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_gen_rst.py
=> BUG Remove if final block empty

continuous_integration/azure/install.sh
=> MAINT Specify Jinja2 version in azure Python nightly

continuous_integration/azure/install.sh, doc/index.rst
Also removes old travis comment in `install.sh`
=> DOC Update CI links in index.rst

.circleci/config.yml
Work around https://github.com/pypa/pip/issues/9655 on CircleCI
=> ENH: PyQt5

doc/advanced.rst, doc/conf.py, doc/configuration.rst
Related to #780
Hopefully it is correct.
=> DOC Add segment on CSS styling

README.rst, doc/projects_list.rst
=> Add Optuna to "Who uses Optuna"

doc/projects_list.rst
These are:
* https://github.com/automl/auto-sklearn
* https://github.com/openml/openml-python/
=> DOC: add 2 projects using sphinx gallery

sphinx_gallery/tests/test_full.py
Locally I have this failure, let's see if it fixes the problems in https://github.com/sphinx-gallery/sphinx-gallery/pull/810
=> MAINT: Fix test for links

sphinx_gallery/_static/gallery.css
Closes #815
Thanks @jorisvandenbossche for the suggested fix, will merge once CIs come back happy. I've tested locally and everything looks good on MNE-Python.
Also happy to let you make the PR but I figured this would be quicker :)
=> BUG: Fix CSS selector

README.rst, doc/index.rst
Remove appveyor, add circle CI
=> DOC Update CI badge

doc/projects_list.rst
closes #755
Have only added projects already included in interpshinx list in our conf.py
=> DOC Use intersphinx references in projects_list.rst

doc/advanced.rst
Adds section on CSS
closes #760
=> DOC Add section on altering CSS

CHANGES.rst, sphinx_gallery/__init__.py
Will do release this afternoon.
=> Release 0.9.0

README.rst, doc/projects_list.rst
=> Add TorchIO to users list

sphinx_gallery/gen_rst.py
Have been meaning to do some refactoring and `execute_code_block` is quite long ~133 lines so thought it was a good place to start.
No strong opinions on what is here and happy to make changes.
=> Refactor execute_code_block in gen_rst.py

continuous_integration/azure/install.sh
Try pinning vtk version <=9.0.1 as suggested in: https://github.com/sphinx-gallery/sphinx-gallery/pull/844#issuecomment-874800615
More details: https://github.com/enthought/mayavi/pull/1050
=> MAINT: Fix mayavi build hang

.circleci/config.yml
Specify vtk <=9.0.1 for cricleci, should have done this in #848 but forgot.
=> MAINT: Fix mayavi build hang circleci

sphinx_gallery/gen_rst.py
Fixes issue with special characters in Binder URLs for branch names and file paths. No characters that need quoting are allowed for GitHub _orgs_ and _repos_
=> BUG URL quote branch names and filepaths in Binder URLs

doc/advanced.rst
closes #804
@larsoner just wanted to add this small PR before release. I have my setup back and happy to do the release once this is in, thanks!
=> DOC Update reset_modules documentation

sphinx_gallery/load_style.py
closes #878
Hope you don't mind I gave this a go @pmeier, thought we'd try to get it in the next patch release.
Does this fix the problem?
=> Add imagesg directive in load style

CHANGES.rst, doc/advanced.rst, doc/configuration.rst, sphinx_gallery/__init__.py
Also updates docs to standardise line length.
=> Release0.10.1

.circleci/config.yml, .gitignore, MANIFEST.in, doc/Makefile, doc/conf.py, doc/index.rst, pyvista_examples/README.rst, pyvista_examples/plot_collisions.py, pyvista_examples/plot_glyphs.py, pyvista_examples/plot_lighting.py, pyvista_examples/plot_ray_trace.py
Finally getting around to https://github.com/sphinx-gallery/sphinx-gallery/issues/441#issuecomment-648133448
I thought it'd be cool to show of some of PyVista's examples here and point folks over to what we've built using Sphinx-Gallery -- it's such an awesome Sphinx extension!!
Hopefully adding this isn't a burden on the CI since you're already supporting Mayavi, but we'll see....
cc @akaszynski
Preview:
=> Add PyVista examples!

.circleci/config.yml
Should fix https://app.circleci.com/pipelines/github/sphinx-gallery/sphinx-gallery/975/workflows/87d0e110-3070-40bc-9941-2fa761900b39/jobs/2484
=> FIX: Pin pyvista

CHANGES.rst, doc/conf.py, doc/faq.rst, sphinx_gallery/_static/sg_gallery.css, sphinx_gallery/backreferences.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_backreferences.py, sphinx_gallery/tests/test_full.py, sphinx_gallery/tests/test_gen_gallery.py
=> Css grid for thumbnails

.gitignore, azure-pipelines.yml, continuous_integration/azure/install.sh, setup.cfg
=> FIX: Azure

doc/conf.py, sphinx_gallery/directives.py
=> [WIP] Bugfix missing parent div for mini gallery

sphinx_gallery/tests/tinybuild/conf.py
First commit is empty just to replicate the error(s).
=> MAINT: Fix CIs

doc/getting_started.rst, sphinx_gallery/gen_gallery.py, sphinx_gallery/tests/test_gen_gallery.py
This should resolve #921. I am very unsure if that is the right place or the right style for a) fixing this issue and b) unittesting.
I am happy to refactor to meet your styles/philosophy.
=> Ensures right builder conifg

azure-pipelines.yml, doc/conf.py, sphinx_gallery/gen_gallery.py
This should fail because of the bad linking. Then we can fix it
cc @alexisthual
=> MAINT: Use -nWT --keep-going on Azure

sphinx_gallery/downloads.py, sphinx_gallery/gen_rst.py
some syntax error in the member downloads.CODE_DOWNLOAD and downloads.CODE_ZIP_DOWNLOAD which were not interpretate right in the resulting *.rst file.
=> syntax error fix in sphinx_gallery.downloads

README.rst, doc/projects_list.rst
Code : https://github.com/radis/radis
Gallery : https://radis.readthedocs.io/en/latest/auto_examples/index.html
=> added RADIS in Who uses Sphinx-gallery ?

doc/projects_list.rst
=> BUG: Fix links

CHANGES.rst, azure-pipelines.yml, continuous_integration/azure/install.sh, dev-requirements.txt, requirements.txt, sphinx_gallery/backreferences.py, sphinx_gallery/directives.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_full.py
Closes #992
cc @rflamary @mthrok @alexisthual I plan to merge and cut 0.11.1. I tested locally on `tinybuild` and on MNE-Python and it fixed it both places
=> BUG: Fix single column example

CHANGES.rst, sphinx_gallery/__init__.py
=> MAINT: Bump to 0.11.1

doc/advanced.rst
=> Fix outdated import

azure-pipelines.yml, continuous_integration/azure/install.sh, dev-requirements.txt, sphinx_gallery/tests/test_full.py
Failures in https://github.com/sphinx-gallery/sphinx-gallery/pull/1027 look unrelated, let's see if they are.
=> MAINT: Check CI status

sphinx_gallery/gen_gallery.py
Fixes https://github.com/sphinx-gallery/sphinx-gallery/issues/1024
=> [BUG, MRG] fix issue with api usage dict

sphinx_gallery/gen_gallery.py
This is going to be hard to test without a run that uses `sphinx-autoapi`.
@tamasgal can you try this branch? Something like `pip install https://github.com/larsoner/sphinx-gallery/zipball/bug` should do it. If it fails, can you use the verbose mode again so I can see the failing traceback?
Closes #1093
=> BUG: Fix bug with show_api_usage

.github_changelog_generator, CHANGES.rst, doc/maintainers.rst, sphinx_gallery/__init__.py
=> MAINT: Prepare for release

README.rst
I like badges, so I can for sure consider adding more. But PyPI/conda-forge versions and codecov percentage seems fair.
Options include:
* Number of commits since last download https://img.shields.io/github/commits-since/sphinx-gallery/sphinx-gallery/latest
* Downloads https://img.shields.io/pypi/dm/sphinx-gallery
* License https://img.shields.io/github/license/sphinx-gallery/sphinx-gallery or https://img.shields.io/pypi/l/sphinx-gallery
=> MNT: Add a few badges

examples/README.txt
As discussed here: https://github.com/sphinx-gallery/sphinx-gallery/commit/caef7831d8f42f6fa6a660b376a1e9e02809030b#r122236474
=> DOC Update basics gallery name

sphinx_gallery/gen_gallery.py
* make `init_api_usage` private
* More explicit name for `clean_file`
=> MAINT Lint api usage

doc/conf.py
This should fix the failure from #1125, let's see...
=> MAINT: pydata-sphinx-theme

doc/configuration.rst
=> DOC Clarify sub level example gallery

doc/advanced.rst, doc/configuration.rst
Follow on from #1278, just thought i'd mention it in the scraper section.
=> DOC Mention `image_srcset` config in scraper section in `advanced.rst`

pyproject.toml
=> MNT: Add ipython to dev dependencies

sphinx_gallery/gen_gallery.py
`gallery_conf` is dict and does not need to be returned if changed in function.
=> MNT: Fix `gallery_conf` changes do not need to be returned

.circleci/config.yml
=> Update pyvista in doc CI

doc/configuration.rst
deals with https://github.com/sphinx-gallery/sphinx-gallery/pull/877#issuecomment-2253683803
@larsoner @QuLogic I am not certain I 100% followed your comments so please let me know if the doc update is not right. Thank you
=> DOC add note on filtering joblib warnings

doc/configuration.rst, pyproject.toml, sphinx_gallery/tests/conftest.py, sphinx_gallery/tests/test_gen_gallery.py, sphinx_gallery/tests/test_load_style.py
See: https://github.com/sphinx-gallery/sphinx-gallery/pull/1360#issuecomment-2263163511
`conf_file` fixture and mark were name the same which makes it confusing.
=> MNT Change mark and fixture names for adding files

doc/configuration.rst
=> DOC Improve doc about joblib warnings

.github/workflows/tests.yml, doc/configuration.rst, sphinx_gallery/gen_gallery.py, sphinx_gallery/gen_rst.py, sphinx_gallery/tests/test_gen_rst.py
=> Add block-level `sphinx_gallery_capture_repr_block` setting

.github/workflows/label-check.yml
See: https://github.com/sphinx-gallery/sphinx-gallery/pull/1423#issuecomment-2605382648
I think we have the same problem as in https://github.com/orgs/community/discussions/30923
Not sure on this though due to my poor bash skills, please have a look @larsoner thank you!
=> Fix label checker workflow

README.rst
Hello!
I'm a bug fan of sphinx gallery and this quick PR adds 3 projects where I have collaborated to create nice galleries : POT, SKADA and TorchDR.
=> Add POT, SKADA and TorchDR to the list in README

doc/faq.rst
Added FAQ entries about including notebooks and reStructuredText files in galleries.
=> Update FAQ with notebook and RST file guidance
