sphinx-gallery/sphinx-gallery

doc/_static/theme_override.css
doc/advanced_configuration.rst
doc/conf.py
doc/index.rst
doc/reference.rst
examples/plot_gallery_version.py
examples/plot_strings.py
sphinxgallery/docs_resolv.py
sphinxgallery/gen_gallery.py
sphinxgallery/gen_rst.py

This pull request includes my proposal for the names in the configuration/setup of the sphinx-gallery.
* I decided to keep the configuration in a dictionary, and a nested dictionary in it for the reference urls of other documentations. Keywords refering to directories have the _dir suffix.
* Keyword `doc_module` is a string or list of stings containing the local modules for which examples are provided, and one later wants to link when documenting modules.
example: http://sphinx-gallery-local.readthedocs.org/en/config/advanced_configuration.html#establishing-local-references-to-examples
* Keyword `reference_url` is a new dictionary containing module name and url to online documentation of that same module. This is the one that allows to put the links in each command of the python scripts …

Naming convention for configuration

---

sphinxgallery/__init__.py
sphinxgallery/gen_gallery.py

Workaround for the adequate update of the sphinx-gallery configuration dictionary once noplot is used
https://github.com/nilearn/nilearn/issues/554

Workaround no-plot bug

---

sphinxgallery/gen_gallery.py
sphinxgallery/gen_rst.py

This change was first motivated by #29 to remove the explicit use of the _build directory path in any instruction in sphinx-gallery(PR #30 also related).
The hack in sphinx-gallery that cleans the images is now more specific as it now scans for png images with the sphx_glr prefix that should be only created by us. Is solves the competition with the maplotlib plot directive #8 at least in my known case.

Image clean

---

sphinxgallery/docs_resolv.py
sphinxgallery/tests/test_docs_resolv.py

This is established to fix #29 saving the shelve file of documentation api indexes is the gallery_dir path set by the user in his configuration file. The shelve does not get copied by sphinx into the final output html directory.

Shelve now stored in gallery_dir

---

sphinxgallery/backreferences.py
sphinxgallery/tests/test_backreferences.py

Recently I discovered that in python 2.6 one needs to specify(at least with positional arguments) which variable needs to be replaced in a string using the format method. So this PR specifies the thumbnail template string with the replaced variable names. It additional provides a simple test.
Side question. Do we have to support python 2.6. Scikit-learn does support it, but will users be building the docs in python 2.6?

Test over the thumbnail generator

---

sphinxgallery/gen_rst.py
sphinxgallery/tests/reference_parse.txt
sphinxgallery/tests/test_gen_rst.py

plus test. Also not adding text block if it contains only whitespace hence the modification of reference_parse.txt.
Fix #49.

Fix gen_rst.split_code_and_text_blocks with comment right after the docstring

---

sphinxgallery/backreferences.py
sphinxgallery/tests/test_backreferences.py

In the LaTeX builds of scikit-learn docs, we land up with (gallery) thumbnails showing immediately before examples in which the image is shown again. The thumbnails should not be shown in the latex docs.
While the API-to-example backreferences are useful in PDF too, there the images bloat everything (they are quite large), and are confusing because they float (not inline). Instead of images in the LaTeX, there should just be a list of links to examples... or the images should be smaller than they're showing in LaTeX.

[MRG+1] BUG fix don't show example thumbnails in latex docs

---

sphinx_gallery/gen_rst.py

In a gallery, we want the simplest examples in the beginning. A good
proxy for simplicity is the amount of code.
This commit adds sorting by the amount of code.

ENH: sort the examples from shortest to longest

---

examples/sin_func/plot_sin.py

Links between gallery examples are a useful feature. I added such a link to one of the ``sin_func`` gallery examples. Maybe this feature could be documented in ``advanced_configuration.rst`` as well?

Illustrated that links between gallery examples are possible.

---

.travis.yml

This closes #78 
The travis-ci test file is accordingly modified to provide a conda virtual environment where the mayavi example is successfully executed and the gallery is build.
I could not reproduce the notified bug, the mayavi example runs as is. Provided one has an X server or or a headless X server running (8d926fd specifically for travis-ci) and the correct pyface version that does not clashes with the sphinx and pygments version. For this case just an up to date version, which fortunately enough does not clash with mayavi either(Its conda version dependencies, require to this date an older version of pyface, but the new one does not seem to give problems, see 4f303c7)

Make Travis test the Mayavi aware version of the Gallery

---

examples/sin_func/plot_sin.py
requirements.txt
sphinx_gallery/gen_rst.py
sphinx_gallery/notebook.py
sphinx_gallery/tests/test_gen_rst.py

This PR addresses #39 
Using the block splitting of the scripts introduced for the notebook styled example. It is now simple to construct an IPython notebook cell by cell.
I now include as a dependency the nbformat which defines the cell nodes of the Ipython notebook.
Code is tidy in the notebooks. The RST text is understood by the Notebook quite fine.
Now that I see on travis python2.6 fails

[MRG+1] IPython notebook parser

---

sphinx_gallery/_static/gallery.css
sphinx_gallery/gen_rst.py

1. The matching on .sphx-glr-script-out+p is too general and could
introduce space where we don't want it. I don't know why it was
dropped in
https://github.com/sphinx-gallery/sphinx-gallery/commit/3a8d9dcef6487f1d89434b2487c160cb37e430fa
This seems an error too me.
2. I have made the space on the right of the output blocks disappear.
While working on a course, I realized that it was distracting.

STYLE: CSS tweak

---

doc/index.rst
sphinx_gallery/gen_gallery.py

This closes #71 
Functions and classes parsed by autodoc try to include backreferences to gallery examples, but examples using some of the functions in a module don't exist. An include warning is thus raised. This avoids such warning, because at least an empty  backreference file is created for every function

[MRG+1] Touch backreferences

---

sphinx_gallery/gen_rst.py

This commit adds vertical between the output of the script and the code
of the script, when there is only one output and it comes on top of the
code (non notebook behavior).
This is to avoid ugly-looking rendering like the following:
https://circle-artifacts.com/gh/nilearn/nilearn/1108/artifacts/0/home/ubuntu/nilearn/doc/_build/html/auto_examples/01_plotting/plot_overlay.html#sphx-glr-auto-examples-01-plotting-plot-overlay-py

[MRG] MISC: add vertical space

---

sphinx_gallery/backreferences.py

I had a problem with Mayavi throwing a `ValueError` during import when using sphinx-gallery. This makes the catch more general and thus safer.

[MRG+1] ENH: Better catch for import

---

README.rst

Closes #87 
After a scan in Github this are the projects that use Sphinx-Gallery and have an online website with some examples available. Link directs to the respective examples gallery. This list is in the readme. Directly after the presentation. So people entering the github repository can immediately have a felling how the gallery looks like.

List Sphinx-Gallery users websites

---

.travis.yml
examples/plot_quantum.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

Previously, [our] (https://github.com/mne-tools/mne-python) code had unicode in the `stdout` which gave:
```
../examples/preprocessing/plot_maxwell_filter.py is not compiling:
Traceback (most recent call last):
File "/home/larsoner/custombuilds/sphinx-gallery/sphinx_gallery/gen_rst.py", line 474, in execute_script
my_stdout = my_buffer.getvalue().strip().expandtabs()
File "/usr/lib/python2.7/StringIO.py", line 271, in getvalue
self.buf += ''.join(self.buflist)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 36: ordinal not in range(128)
```
Modified a test that fails on `master` and passes on this PR.
Works on my system (™) on Py3k and Python 2.7.
Closes #18.
Closes #19.

[MRG+1]: Allow unicode in code and outputs

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

I think there was just a typo in the string that the code output gets formatted into.

Remove extra indentation

---

sphinx_gallery/gen_rst.py

There is an issue with indexing mayavi figures. This manifests itself in thumbnail figures not being rendered here https://circle-artifacts.com/gh/mne-tools/mne-python/621/artifacts/0/home/ubuntu/mne-python/doc/_build/html/auto_examples/index.html
See  for example ``plot all-to-all connectivity in sensor space``.
I'm not sure if this is the correct fix, but it seems to at least work around the issue.
cc @agramfort

Fix indexing with mayavi figures.

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

I noticed that when you build tutorials like this https://circle-artifacts.com/gh/mne-tools/mne-python/645/artifacts/0/home/ubuntu/mne-python/doc/_build/html/auto_tutorials/plot_source_localization_basics.html, function ``save_figures`` gets called multiple times (notice the duplicates of the mayavi figure). Therefore the fix in https://github.com/sphinx-gallery/sphinx-gallery/pull/116 alone won't work. I tried this locally on couple of my examples and tutorials and it seems to fix the issue.

Fix to mayavi figure indexing.

---

sphinx_gallery/gen_gallery.py

Now it should work with the two possible configurations of sphinx (with
or without a source directory).
See #115.

Modified path in gen_gallery_rst to solve sphinx config problem

---

sphinx_gallery/_static/gallery.css
sphinx_gallery/gen_rst.py

This is a small style change to make the download buttons of the examples take less vertical space while still being more visible.
I am attaching a screenshot of the new style:

STYLE: tighter and pretty download buttons

---

sphinx_gallery/notebook.py
sphinx_gallery/tests/test_notebook.py

If inline math appears multiple times in the same line it would be joined in the same block. The non-greedy regex fixes that.
If inline math spans over multiple lines, it would not be parsed. The re.DOTALL fixes that
For discussion. The example `plot_quantum.py` uses heavily latex. I noticed the previous bugs from it. It also uses a multiline math that to be rendered correctly in the jupyter notebook it requires to be wrapped with:
```latex
\begin{align}
\end{align}
```
Should I make this the default for the rst syntax:
```rst
.. math: some latex
```

[MRG] Notebook inline math

---

.travis.yml
CHANGES.rst
examples/plot_seaborn.py
sphinx_gallery/gen_rst.py
tutorials/plot_seaborn_notebook.py

If seaborn is loaded in one example, examples afterward keep using its plotting style. This patch clears its presence. I'm still looking for different way to sandbox the python execution.
I'm also getting errors in python3 on the seaborn script.

Seaborn enviroment clean up

---

.gitignore
sphinx_gallery/notebook.py
sphinx_gallery/tests/test_notebook.py
tutorials/plot_notebook.py

Closes #141.
1. Removes some of the offending residual restructuredtext directives:
2. Adds warning/note boxes:
3. Adds image support:
4. Corrects problem with greedy regex for inline math.
Ready for review/merge from my end.

ENH: Improve markdown conversion

---

CHANGES.rst
README.rst
doc/getting_started.rst
doc/reference.rst
sphinx_gallery/downloads.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

To answer #128 I propose this to download all example files per section in python and Jupyter notebooks
I'm still unsure of the presentation. If the download should be in the yellow boxes we use in the files or a simpler plain text. Also if it would be at the start of the example section or at the end.

[MRG] Script downloads

---

sphinx_gallery/_static/gallery.css
sphinx_gallery/docs_resolv.py

The goal is to enable downstream to style the doc-resolv links in code examples specially.

[MRG] CSS: add a CSS class to links in code

---

CHANGES.rst
doc/Makefile
doc/conf.py

In response to the discussion in https://github.com/sphinx-gallery/sphinx-gallery/pull/145#issuecomment-247575808
Here I propose to change the html theme passing an extra variable to the make target. In this case on can build locally the read the docs theme by using
```bash
make html theme=rtd
```
Also all sphinx themes become available. Thus to change to nature theme is as simple as
```bash
make html theme=nature
```
If one does not pass the `theme=value` instruction the `classic` default is taken.

Sphinx themes

---

sphinx_gallery/_static/gallery.css
sphinx_gallery/downloads.py

This PR:
* Fixes the overflow visible in the download buttons (as discussed in https://github.com/scikit-learn/scikit-learn/pull/7354#issuecomment-246689940)
* Centers the buttons correctly
* Make the sphinx-gallery signature slightly less visible (let's not annoy downstream users)
Before, in sphinx-gallery's documentation:
After:
Before in scipy-lectures
After:

[MRG] CSS: improve rendering of download buttons

---

.travis.yml
CHANGES.rst

while working on #151, I hit again the problem of tests not passing on ubuntu. Problem is the seaborn support and requirement for pandas cython for pandas.
I have created a more descriptive test matrix, which loads ubuntu 12 and 14. Ubuntu 14 does not have seaborn either but the pandas version is updated enough to work with seaborn.
After few tests I can't get ubuntu 12 to work without upgrading all python packages with pip.
Travis still claims ubuntu 14 is a test feature and builds on it take longer. That is the reason of the container matrix. All test on conda are ubuntu 12 containers and for ubuntu 14 specific packages the environment is different.

Update travis to drop ubuntu 12 test

---

doc/_templates/breadcrumbs.html

closes #154 
Here I remove the edit from github button in favor of just having a view page source link. You can preview it at my readthedocs build of this PR at http://sphinx-gallery-local.readthedocs.io/en/editgh

RTD theme links to show source not edit on github

---

CHANGES.rst
sphinx_gallery/gen_rst.py

closes #153 
This includes an additional warning message when loading the Agg backend if matplotlib has loaded any other backend before.

Warn the user to set the Agg backend

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

In one of my scripts I want to use `__name__` but in `master` it is not available.

MRG: Add __file__

---

sphinx_gallery/gen_rst.py

This is available since matplotlib 0.98: http://matplotlib.org/api/api_changes.html#changes-for-0-98-x

[MRG+1] Use plt.get_fignums rather than a private helper

---

sphinx_gallery/backreferences.py
sphinx_gallery/tests/test_backreferences.py

Fix #172.
My guess is that backreferences are not used for modules so I excluded modules without attributes from `scan_used_functions`.
Edit: Close #149 as well.

Fix backreferences.identify_names when module is used without attribute

---

sphinx_gallery/_static/gallery.css

This is a tiny backport of a CSS needed for Sphinx-Gallery not to collapse this Scikit-learn website theme.
Code link tooltips used to be shifted to the left to give the impression
they are centered with the link one hovers the mouse. Nevertheless this
floating tooltip collides with the sidebar in the Scikit-learn
documentation.
As a general goal our CSS shall not collide with other projects
templates. Thus this tooltip shall be contained with the codeblock
where the links are.

[CSS] Code link tooltip is left aligned with code

---

appveyor.yml
sphinx_gallery/backreferences.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/py_source_parser.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_docs_resolv.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_notebook.py

Adds AppVeyor and fixes things on Windows (hopefully).
Closes #162.
Closes #176.

[MRG+1]: Fixes for Windows

---

appveyor.yml

This PR is just to make sure this is working as expected. I'll merge it once AppVeyor comes back green and I'll double check that Python 3.5 is used.

[MRG] Add Python 3.5 for AppVeyor

---

doc/conf.py
examples/plot_syntaxerror.py
sphinx_gallery/backreferences.py
sphinx_gallery/py_source_parser.py

As reported in #126 if an example has a SyntaxError gallery build
breaks. This provides the necessary changes to continue build and
raise an error at the end on the summary of errors

[MRG] Build gallery when example has SyntaxError

---

sphinx_gallery/docs_resolv.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py

This does two things:
1. Suppresses output when doing `plot_gallery=False` saying it took 0 seconds to run a bunch of examples that didn't run. It's not very informative, and it makes the sphinx output very long, thus making things like checking for good sphink markup, bad links, etc. harder (what `plot_gallery=False` is mostly used for, I assume).
2. Uses `app.status_iterator` for the last stage of processing where code is embedded. Instead of having tens or hundreds of lines, now the output looks like the rest of sphinx, e.g.:
```
auto_examples[100%] plot_left_cerebellum_volume_source.html
auto_tutorials[100%] plot_ica_from_raw.html
```

ENH: Cleaner output

---

circle.yml

Shamelessly copy from MNE-python Circle CI script not to install conda again

cached conda gives problems in new Circle CI Builds

---

CHANGES.rst
sphinx_gallery/_static/gallery.css
sphinx_gallery/docs_resolv.py

Following the recommendation done on https://github.com/scikit-learn/scikit-learn/pull/7986#issuecomment-265322148, this PR simplifies the tooltips for code links
Currently the tooltip appears immediately after hovering the link and with message "Link to". It is visually uniform in firefox and chromium.
This changes uses title and lets the browser handle this popup which appears after a few seconds of hovering over the link. It also changes "link to"->"View"
Thus in firefox it is similar to the previous one but without the like break
And in chromium is a different style

[MRG] Drop styling of codelinks tooltip use title

---

sphinx_gallery/gen_rst.py
sphinx_gallery/notebook.py

`text2string()` uses `ast.literal_eval()` but `ast` is never imported in the file. So the try-except block is catching a `NameError`?

[MRG] Remove nonfunctional text2string function

---

sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py

PR #187 introduced the use of the `orphan` sphinx directive to avoid the warnings of the gallery examples not being in any toctree. This directive has to be called once per rst file and not before every section, otherwise `:orphan:` is presented in the html file. This PR fixes that behaviour

[MRG] Fix :orphan: sphinx-directive multiple calls

---

CHANGES.rst
circle.yml
doc/Makefile
setup.cfg
sphinx_gallery/backreferences.py
sphinx_gallery/docs_resolv.py
sphinx_gallery/downloads.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

This replaces #133 
As brought back to life by #186, Sphinx-Gallery does not handle the cases when the documentation structure is in a different place than the location of the makefile and the conf.py files.
This PR aims to fix that and preceding issues stated in  #40 #50 #115 #119 #120
For test completeness I know build in circle CI the documentation in various location, with different commands a different themes.
As can be seen from the build logs(https://circleci.com/gh/Titan-C/sphinx-gallery/12?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). The examples are run only on the first build, later builds can take advantage of the cached files as they are referenced in the same locations and the output to the described location. For review. This are the …

[MRG] Better path handling

---

.travis.yml

now that mayavi 4.5 is available through conda, we do not need the work-around of installing a newer pyface with pip.
Just making sure that the CI pass before merging this one.

[MRG] MAINT simplify .travis.yml

---

sphinx_gallery/docs_resolv.py

Fixes part of https://github.com/sphinx-gallery/sphinx-gallery/issues/113. The regular expression was not matching for the first (i.e. also the longest) name.
I have to say I don't understand why the regex `'r(?<!\.)\b` was here ... but I double-check that on sphinx-gallery examples, it does add a link for the longest name.
For example this adds a link to `np.linspace` in this [example](http://sphinx-gallery.readthedocs.io/en/stable/auto_examples/plot_exp.html#sphx-glr-auto-examples-plot-exp-py) and a link to `np.random.RandomState` in this [example](http://sphinx-gallery.readthedocs.io/en/latest/auto_examples/plot_seaborn.html#sphx-glr-auto-examples-plot-seaborn-py).
Obviously adding a test would be good, but I have already spent too much time on this to my liking ...

[MRG] Fix embedded missing link

---

doc/index.rst

Fix #159 
- Include a link to the Github repository in the main page of documentation.
- Include a link in the table of contents

Add link from documentation to Github

---

README.rst
appveyor.yml
sphinx_gallery/backreferences.py
sphinx_gallery/downloads.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_backreferences.py

Closes #183, now downloadable zip files are available and there are no missing gallery examples in the toctree
- Uses forward slashes only inside rst files
- AppVeyor captures artifacts of html build

[MRG] download zip files path

---

CHANGES.rst
doc/faq.rst
doc/index.rst
sphinx_gallery/gen_rst.py

Fix #211 
@amueller does this work for you?

__file__ global variable in script execution

---

CHANGES.rst
sphinx_gallery/gen_gallery.py

Fixes #241 - looks like sphinx changed its API a little bit

fixing sphinx bug

---

sphinx_gallery/backreferences.py
sphinx_gallery/tests/test_backreferences.py

Escape tooltips for any HTML special characters.

---

sphinx_gallery/docs_resolv.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/sphinx_compatibility.py
sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_sphinx_compatibility.py

This PR tries to reduce the console output during a build, as well as pass a lot of status message through the Sphinx logging API. This gives the immediate benefit of matching styling with Sphinx easily. I tried to add colours to various items to match Sphinx appearance, but I'm open to suggestions as to the logging level of the messages.
Before:
[![asciicast](https://asciinema.org/a/122701.png)](https://asciinema.org/a/122701)
After:
[![asciicast](https://asciinema.org/a/122702.png)](https://asciinema.org/a/122702)
Since sphinx-gallery's documentation prints a lot, it might not totally clear, so here's a Matplotlib doc build with the patched branch:
[![asciicast](https://asciinema.org/a/122706.png)](https://asciinema.org/a/122706)
Fixes #230.

Cleanup console output during build

---

sphinx_gallery/docs_resolv.py

`open()` defaults to text mode, invoking the default system encoding. For
files written in utf-8, this results in decde errors on systems where
the default encoding is something else. This is especially problematic
on windows where the default is cp1252.
While I found this problem trying to build docs on Windows, I can reproduce on my mac with:
```sh
LANG=en_US.ascii make clean html
```
Everything seems to work fine just by opening the file in binary mode so that no implicit encoding is assumed.

BUG: Fix reading with non-utf-8 default encoding

---

sphinx_gallery/backreferences.py

Reverts sphinx-gallery/sphinx-gallery#257.
In python 2 the codeblocks are not being properly recognized to embed the documentation links.

Revert "Enforce UTF8 encoding in backreferences"

---

README.rst

In order to build the documentation, developpers also need to install
Seaborn and Scipy.

[MRG+1] [DOC] Added documentation dependencies.

---

.gitignore
.travis.yml
sphinx_gallery/gen_gallery.py

This PR renders parallelization of sphinx build possible. It does not parallelize the build of the gallery itself, but only allows to activate parallel build for the rest of the sphinx build.
The build of the documentation fails on my laptop right now. I'm pretty sure it's unrelated to this patch, but I've activated parallel build in travis to test.

[MRG+1] ENH parallelization is now possible

---

.travis.yml
README.rst
circle.yml
doc/advanced_configuration.rst
doc/conf.py
sphinx_gallery/docs_resolv.py
sphinx_gallery/gen_gallery.py

Check for both `http:` and `https:` where necessary, and then use secure links in as many places as possible.

Allow and use https links where possible

---

CHANGES.rst
examples/plot_sys_argv.py
sphinx_gallery/gen_rst.py

Fix #251.
The fix is not the nicest one (maybe changing `sys.argv` inside a `try` clause and changing it back in `except` would make it a bit better) but it works ...

Fix for when sys.argv is used in examples

---

circle.yml
docs_deploy.sh

Read the docs has built our docs for a long time, and it has some limitations. For example we can not build the examples gallery for mayavi. And with PR #244, we need to have the jupyter notebooks on a github repository to use binder.
This PR builds the documentation on CircleCI and if succesful it pushed the results to github pages.
Now the build address is 
https://sphinx-gallery.github.io
For the moment it will only build master branch. 
I image we can slowly move towards this website and drop readthedocs.

Push the docs from Circle CI into github

---

sphinx_gallery/backreferences.py

For example, `matplotlib.pyplot.figure` can be shortened to `matplotlib.figure`, but the former is a function (that is used a lot) while the latter is a module (which is generally used much less).

Ensure shortened module path points to expected object.

---

doc/Makefile
doc/advanced_configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py

Closes #282.
WIP because #279 needs to be merged first, then I can properly document how to get different thumbnail sizes.
In #277 @Titan-C you suggested this:
> I might say start clustering it with other options for the thumbnail, like the default image... Of course that would break backwards compatibility.
Here I've decided to avoid the step of combining keys. It seems like it could create a bit of deprecation pain for little gain in terms of readability.
I also added the "show" `Makefile` option because I've found it helpful previously, but I can split that off or remove it if need be.

MRG: Add thumbnail_size option

---

doc/advanced_configuration.rst
doc/conf.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/sorting.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_sorting.py
sphinx_gallery/tests/testconfs/src/plot_1.py
sphinx_gallery/tests/testconfs/src/plot_2.py
sphinx_gallery/tests/testconfs/src/plot_3.py

Closes #275.
Closes #278. (Take over of this PR.)
This adds sort keys for sorting within subsections. I don't need explicit reordering currently (filename-based is good enough for now) so I didn't bother implementing it for now. But it at least sets up the framework for it later.
~~WIP for now because I'm not updating the doc until #279 is merged and I can rebase to avoid conflicts.~~

MRG: Allow sorting subsection files

---

.travis.yml
sphinx_gallery/py_source_parser.py

python/cpython#46 or bpo-29463 added docstring as a property to the module class that comes out of AST (so the free strings no longer appear an the first element in the parsed files).

Fix py37 changes

---

sphinx_gallery/docs_resolv.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py

Consistently with other logs output by sphinx, don't capitalize the
first letter of the log.  Slight fixes to whitespace.

Minor changes to log format.

---

sphinx_gallery/docs_resolv.py

This makes the logging of links resolution similar to the logging of
gallery generation:
generating gallery...
generating gallery for examples... [100%] foo.py
embedding documentation hyperlinks...
embedding documentation hyperlinks in examples... [100%] foo.html
followup to #285.

Minor fix to format of logs.

---

sphinx_gallery/gen_gallery.py

Without this change, I always get this warning:
```
WARNING: The config value `plot_gallery' has type `unicode', defaults to `bool'.
```
I don't love this fix. I assume only bool values should be allowed, but there is an `eval` later in the code that looks like it's meant to accommodate string values, so this might actually be a correct workaround.

MRG: Fix warning

---

doc/conf.py
sphinx_gallery/docs_resolv.py
sphinx_gallery/tests/test_docs_resolv.py

Over at MNE we are getting:
```
embedding documentation hyperlinks...
Exception occurred:
File "/home/ubuntu/mne-python/sphinx-gallery/sphinx_gallery/docs_resolv.py", line 50, in _get_data
data = StringIO(data)
TypeError: initial_value must be unicode or None, not str
```
I have a fix but I want to see if I can expose it first (TDD!).

MRG: Fix gzip/BytesIO error

---

.travis.yml

This should fix the Travis build failure seen in https://github.com/sphinx-gallery/sphinx-gallery/pull/292#issuecomment-328479686.
Travis provides numpy in its default virtual env and I am guessing that they upgraded the version recently. In any case we want to have control over the numpy we are using in this case the numpy from apt-get
I did some minor clean-ups in .travis.yml while I was at it.

[MRG] Deactivate virtualenv provided by Travis

---

sphinx_gallery/gen_gallery.py

Allows one to require a version from sphinx, see
http://www.sphinx-doc.org/en/stable/config.html#confval-needs_extensions
http://www.sphinx-doc.org/en/stable/extdev/index.html#extension-metadata
Not doing `from . import __version__` as this would also set the version
of the submodule.

Report version to sphinx.

---

.gitignore
circle.yml
doc/advanced_configuration.rst
doc/conf.py
doc/reference.rst
setup.cfg
sphinx_gallery/docs_resolv.py
sphinx_gallery/downloads.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_docs_resolv.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/tinybuild/Makefile
sphinx_gallery/tests/tinybuild/_templates/module.rst
sphinx_gallery/tests/tinybuild/conf.py
sphinx_gallery/tests/tinybuild/examples/README.txt
sphinx_gallery/tests/tinybuild/examples/plot_numpy_scipy.py
sphinx_gallery/tests/tinybuild/index.rst
sphinx_gallery/utils.py

Closes #287.
Simplifies link resolution by using `intersphinx`.
~~I'm not sure the best way to test this. I was doing it locally by having a small `testbuild` directory with a `conf.py`, `index.rst`, `examples/plot_numpy_scipy.py`. I could turn this into a test if it seems useful. Would the best way be to directly include the files, copy them to a tempdir, call `Sphinx(...)`, and check the output links to ensure they contain links to numpy/scipy/matplotlib docs, as they should?~~

MRG+1: Use intersphinx

---

circle.yml

Installing the texlive distribution in Circle CI, takes some time because Ubuntu by default installs some recommended packages. This PR avoids installing those recommended packages, which reduces the download time and install time. Build time drops by 1:30 mins

Don't install latex recommended in Circle CI

---

.travis.yml

to avoid pytest_cov PluginValidationError.

[MRG] Require six>=1.10 in ubuntu build

---

CHANGES.rst
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

Combining all output together for a long-running example can cause timeouts on CI, so send output to the log immediately.
Fixes #301.

Log example output as it happens.

---

.travis.yml
continuous_integration/travis/install.sh
continuous_integration/travis/test_script.sh

Some maintenance tasks while I was at it:
- move part of .travis.yml to separate scripts
- use miniconda3 rather than miniconda2 installer
- use INSTALL_MAYAVI env variable
- remove python nightly build (it's been failing for a while and has been ignored because it is in allowed_failure mode). I don't think it makes sense to test on python 3.7 on each PR I would say anyway. Something more useful IMHO would be to have a cron build testing sphinx master.

[MRG] Add codecov support

---

sphinx_gallery/_static/gallery.css
sphinx_gallery/binder.py
sphinx_gallery/downloads.py
sphinx_gallery/gen_rst.py

The binder badge stands a bit on its own and I feel it should be on the same footing as the other download button (download .py + download .ipynb).
About the CSS part, I copied and pasted sphx-glr-download. The thing is that there the rule `div.sphx-glr-download a` was coloring the background around the binder badge and it did not look that great. Any improvements, let me know.
I'll paste links or snapshots once Circle finishes on this PR.

[MRG] Align binder badge with other download buttons

---

sphinx_gallery/binder.py

This prevents cookies used in mybinder.org from being sent 
when requesting the badge, enhancing privacy.
https://github.com/jupyterhub/binderhub/issues/379 for original
issue about this.

[MRG] Use static.mybinder.org for badge image

---

doc/advanced_configuration.rst
sphinx_gallery/binder.py
sphinx_gallery/tests/test_binder.py

This attempts to clarify the instructions around Binder configuration. I'm going through the process of setting this up on some other repos to figure out where it's confusing / unclear / etc. It also adds the `filepath_prefix` option to the configuration, in case people put their documentation in a sub-folder of their repository (e.g. matplotlib puts theirs in one sub-folder per version, such as `1.2.3` etc).

clarifying Binder instructions and adding filepath prefix option

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

This makes an example description optional (title only is okay) by using the title as the description if it's not provided. The alternative is to just use `''`, but this seemed less useful given how the intro paragraph is used alter.
#232 was already fixed, this just adds an explicit test of it.
Closes #232.
Closes #222.

MRG: Allow title only -> use title as first paragraph

---

appveyor.yml
continuous_integration/travis/test_script.sh
setup.cfg
setup.py

This is very likely not used and makes the Python 3.4 build fail for some obscure reasons (see https://travis-ci.org/sphinx-gallery/sphinx-gallery/jobs/340477597 for example).

[MRG] MAINT: remove python setup.py test related things

---

CHANGES.rst
sphinx_gallery/gen_rst.py

Fixes #319. 
It is not used by anyone to the best of my knowledge. I did a github search for SKLEARN_DOC_OPTIPNG and only found matches in `gen_rst.py` files. scikit-learn is not using it even if this optimization originates from scikit-learn (see https://github.com/scikit-learn/scikit-learn/pull/2487).
We could consider a deprecation period but given how unlikely this is that this feature is used I am not sure this is worth it.

[MRG] Remove optipng optimization

---

sphinx_gallery/docs_resolv.py

This fixes compatibility with Sphinx 1.7
If you are happy with this, would it be possible to do a quick bugfix release? ReadTheDocs has now updated to Sphinx 1.7, so I think any project using sphinx-gallery on RTD is likely to run into this issue.
Fixes #351

Fix compatibility of SphinxDocLinkResolver with Sphinx 1.7

---

CHANGES.rst
doc/advanced_configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/py_source_parser.py
sphinx_gallery/tests/tinybuild/examples/__init__.py

Hopefully the doc changes are clear enough, but this allows skipping some files entirely (i.e., not parsing or adding them to the gallery).
Closes #262.

MRG: Add ignore_pattern

---

README.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_gen_gallery.py

so adding it to the fast set up page.

DOC backreferences_dir is now mandatory

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

I tried using sphinx-gallery from master in scikit-learn and I found that https://github.com/sphinx-gallery/sphinx-gallery/pull/345 introduces a regression in a edge case, where the title starts with a space, i.e. your example starts with something like this:
```py
"""
======================
The title
======================
"""
```
I also added more tests for extract_intro_and_title. The detection is based on regex and I feel is as good as the previous one. I tried a docutils based solution using `docutils.core.publish_doctree` (I am guessing we could even check that the first paragraph is a title if we go this way) but I did not get anywhere convincing in a reasonable amount of time.
Note: to make a long story short, the title found by sphinx-gallery was empty before #345 but in practice …

[MRG] Fix title detection logic.

---

.travis.yml
continuous_integration/travis/install.sh

This allows to detect possible problems with sphinx before it is released. It will be run as a daily cron job because rather than in PRs because most of the time sphinx master failures are not related to PR changes but to changes in sphinx.
We do something similar in scikit-learn to test against numpy-dev, scipy-dev and cython-dev and this has proved very useful to feed back issues upstream and get them ironed out before the next release.

[MRG] Add Travis sphinx master cron job

---

sphinx_gallery/_static/gallery.css
sphinx_gallery/downloads.py
sphinx_gallery/gen_rst.py

This is my attempt at removing the floating right download buttons , which I feel is just too hard to configure right by default for a majority of sphinx themes, sorry @GaelVaroquaux ... 
There is a little bit of (at least for me) advanced CSS so that the link to the example from the gallery show the note (i.e. it behaves as if you go to the example section and then scroll up a bit so that you can see the note).
Comments more than welcome!
See #340 as well.

[MRG] Add note at the beginning of the example to the download section at the bottom

---

sphinx_gallery/gen_gallery.py

When using the "separate source and build" layout, sphinx-gallery
creates a spurious (and ultimately empty) "examples/" directory next to
the Makefile, whereas the correct place for that directory is
"source/examples".  It is in fact not necessary to pre-create that
directory, because generate_dir_rst also contains the snippet
if not os.path.exists(target_dir):
os.makedirs(target_dir)
which will create the *correct* examples/ directory.

Don't create spurious examples/ directory.

---

sphinx_gallery/downloads.py
sphinx_gallery/tests/tinybuild/conf.py

If the user enters in the conf.py paths that end by '/', such as
'examples/', the filename of the downloads was '_python.zip'. This
commit fixes it.

[MRG] Fix: Gallery name for paths ending with '/'

---

sphinx_gallery/gen_rst.py

This PR adds support for custom default thumbnails with transparency values. Up to now, the alpha value in RGBA PNG images is simply discarded, resulting in side effects like a black box surrounding the image.

Support for custom default thumbnails in 'RGBA' space

---

sphinx_gallery/docs_resolv.py

scikit-learn uses a layout which contains DOCUMENTATION_OPTIONS, see [this](https://github.com/scikit-learn/scikit-learn/blob/20cb37e8f6e1eb6859239bac6307fcc213ddd52e/doc/themes/scikit-learn/layout.html#L86).
This is related to https://github.com/sphinx-gallery/sphinx-gallery/pull/352, so pinging @astrofrog in case he has some objection.

[MRG] Fix version parsing for scikit-learn doc

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

We should probably use `none` as the markup language for outputs. This is more reflective of how they are rendered in the terminal (a key goal of SG). It also takes care of weird, unexpected formatting of log messages that the default `python` interpretation causes.
The only downside I can see is that `repr`s that were previously formated to look like Python objects no longer will be. But I'd argue this is reasonable behavior since this is more like what a terminal would display when you actually execute the commands.

FIX: Use unstyled pygments for output

---

CHANGES.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/testconfs/index.rst

Apply a filter to examples_not_expected_to_pass to validate that they where
actually run.
Put color to error messages header so that they can be easily found on
sphinx log.
Fix #335.

Fix surprising interaction between file_pattern and expected_failing_examples

---

sphinx_gallery/tests/test_gen_gallery.py

I suspect that this will die on older versions of Sphinx, in which case I'll probably add a context manager to the `sphinx_compatibility` submodule.

FIX: No more workaround

---

sphinx_gallery/gen_gallery.py

spelling fix in summarize_failing_examples function name

spelling fix

---

.circleci/config.yml
doc/_templates/module.rst
doc/advanced_configuration.rst
doc/conf.py
doc/index.rst
doc/maintainers.rst
examples/plot_function_identifier.py
sphinx_gallery/backreferences.py
sphinx_gallery/py_source_parser.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/_templates/module.rst
sphinx_gallery/tests/tinybuild/conf.py
sphinx_gallery/tests/tinybuild/examples/plot_future_imports.py
sphinx_gallery/tests/tinybuild/examples/plot_numpy_scipy.py
sphinx_gallery/tests/tinybuild/examples/plot_second_future_imports.py

Adds to backreferences any function/class that gets `:func:` or `:meth:`'ed in the docstring. This should be particularly useful for things like `matplotlib.axes.Axes` and similar classes that get instantiated only indirectly.
Closes #205.

MRG: Add refs from docstring to backrefs

---

doc/advanced_configuration.rst
doc/conf.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/notebook.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_notebook.py
sphinx_gallery/tests/test_utils.py

This adds a configuration parameter `first_notebook_cell` that lets users choose what text goes in the first cell of created notebooks. By default this remains the same (`%matplotlib inline`).
This could be useful for either other packages that need their own special configuration in a notebook context, or for people that want to run the notebook with the "interactive" matplotlib setting (`%matplotlib notebook`).
closes #388 and relevant to https://github.com/matplotlib/matplotlib/issues/11415

adding ability to customize first cell of notebooks

---

.travis.yml
continuous_integration/travis/install.sh

Sometimes `conda` does not resolve dependencies fully. Let's see if this makes CIs green. Currently we have one failing from the cron job:
https://travis-ci.org/sphinx-gallery/sphinx-gallery/jobs/421905303

FIX: Travis

---

sphinx_gallery/gen_rst.py

When describing a gallery subsection or the main gallery one writes
in the README.txt file which supports RestructuredText syntax and one
should put references for the headings.
But because one can forget an the seems to be no conflict in Sphinx if a
header has to references Sphinx-Gallery prepends an automatically
generated label for each subsection
Fix #127

Include a reference for each gallery subsection

---

doc/conf.py

Whilst working on the Reproducible Builds effort [0], we noticed
that sphinx-gallery could not be built reproducibly.
Patch attached that removes the "Total running time of the script"
messages from the documentation build.
(There is some filesystem-related unreproduciblity that remains, alas.)
This was originally filed in Debian as #901307 [1].
[0] https://reproducible-builds.org/
[1] https://bugs.debian.org/901307

Drop "Total running time" when generating the documentation

---

.travis.yml

Our CRON job [failed](https://travis-ci.org/sphinx-gallery/sphinx-gallery/jobs/426532591#L761) because:
```
ERROR: Sphinx requires at least Python 3.5 to run.
```
This PR thus removes the 2.7 + Sphinx `master` cron job.

MRG: Remove outdated cron job

---

setup.cfg
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py

As I was eradicating warnings during sphinx builds for MNE, I came across a DeprecationWarning and a warning about `\`. This fixes those.

MRG: Fix for newer sphinx

---

sphinx_gallery/__init__.py

We should have bumped to 0.3.dev0 immediately after pushing 0.2.0 out the door in June.

FIX: Bump version

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py

This PR is for addressing the need to style timing block by adding a CSS class `sphx-glr-timing` class to `<p>`.

Add dedicated class for timing related block

---

examples/local_module.py
examples/plot_exp.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/tinybuild/examples/local_module.py
sphinx_gallery/tests/tinybuild/examples/plot_numpy_scipy.py

This patch allows to import a module placed in the same folder as the examples when executing the example by adding the current directory to the sys.path.
I used a deepcopy to restore the sys.path to the original state (before running the example).
This patch relates to a problem we are having on https://github.com/matplotlib/matplotlib/pull/9402
I am honestly not entirely convince that sphinx-gallery *should* support this, as I think that good examples are self-contained examples.

[MRG] FIX import local modules in examples

---

setup.cfg
sphinx_gallery/backreferences.py
sphinx_gallery/tests/test_gen_gallery.py

On the latest `master` run we got:
```
E       RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
E       Please use node.get_closest_marker(name) or node.iter_markers(name).
E       Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
```
i.e., we get a DeprecationWarning from pytest. This works around it.
We also get warnings from `Sphinx` about `'U'` mode, which we can safely ignore.
Will merge once CIs are happy to keep things green.

MRG: Fix for latest pytest

---

sphinx_gallery/sorting.py

This PR solves the copy-pasted docstring for the [`FileNameSortKey`](https://sphinx-gallery.readthedocs.io/en/latest/gen_modules/sphinx_gallery.sorting.html#sphinx_gallery.sorting.FileNameSortKey) class.

FIX: correct sorting docstring for the FileNameSortKey class

---

.travis.yml
continuous_integration/travis/after_success.sh
continuous_integration/travis/install.sh

Activating travis on 3.7 and nightly build of latest dev (with allowed failure, currently python 3.8 which is in pre-release, and apparently breaks sphinx-gallery (unchecked)).

Activating travis on pre-release of python

---

doc/configuration.rst
doc/getting_started.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_gallery.py

closes https://github.com/sphinx-gallery/sphinx-gallery/issues/435
this adds some notices to the documentation to remind people that SG will
only run scripts that begin with `plot_` by default - we've had a few people
get confused because they didn't realize that this was the default behavior.
@larsoner this doesn't implement your idea of raising a warning if no
executable scripts are found, mostly because I couldn't figure out where's the
right place for that to happen in the code. If you like, feel free to push
to this PR!

adding notes for filename

---

.travis.yml
continuous_integration/travis/install.sh

Python 3.4 reaches EOL in a few weeks, and it would be good to use Mayavi on a Py3k run.

MAINT: Drop 3.4, add mayavi to one

---

sphinx_gallery/gen_gallery.py

Tiny bugfix for names that can end in underscores like `my_example_.py`, which can cause RST parsing problems. Fix it by rendering it as code (which looks better anyway IMO).
@drammock can you see if this fixes your problem with names that end in underscores in MNE?

BUG: Fix execution time writing

---

sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py

When building the MNE doc on OSX I sometimes got:
```
File "/Users/larsoner/python/sphinx-gallery/sphinx_gallery/gen_rst.py", line 410, in _get_memory_base
memory_base = max(memory_usage(proc, interval=1e-3, timeout=timeout))
TypeError: '>' not supported between instances of 'NoneType' and 'float'
Exception occurred:
File "/Users/larsoner/python/sphinx-gallery/sphinx_gallery/gen_rst.py", line 410, in _get_memory_base
memory_base = max(memory_usage(proc, interval=1e-3, timeout=timeout))
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```
It turns out sometimes the last entry in the list returned by `memory_usage` was `None`, so now we cull that from the list. It's difficult to write a test for this, so no new test has been added.
Once it worked, sometimes I would …

FIX: Minor fixes for memory profiling

---

.circleci/config.yml
sphinx_gallery/__init__.py

Instead of building multiple styles that we don't use (see #461), let's just build the one that we do.
Also bump version to `0.4.0.dev0`

MAINT: Simplify CircleCI build

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

Fixes #473.
I'm not sure if there is some assumption on the termination of `bcontent`. Text blocks from rST seem to already end with a newline, docstrings don't. This patch does not rely on any assumption and generates correct rST for both cases.
The test seems a bit longish, But I would like to test the full source to rST code conversion. Just creating blocks manually and passing them to `rst_blocks()` seems a bit fragile, because the code is sensitive to newlines at the end. OTOH calling `generate_file_rst()` seems too broad since it generates a lot more stuff like the thumbnail and writes everything to files. Please advise if I should modify the test.

Fix ReST block after docstring

---

sphinx_gallery/_static/gallery.css

Previously the 'Out:' label was aligned at the top of the block and not with the first line.
This results in an awkward appearance in particular for single line output:
This PR fixes this:
The layout appears to be a bit of a hack anyway because the rST code is
~~~
Out:
.. code-block:: none
{0}\n
~~~
So 'Out:' is its own paragraph that would naturally appear above the code. The margin shifting in `.sphx-glr-script-out .highlight` puts it back up. I've shifted the output text down by 0.7em and conversely shifted the code back up by the same amount because it's relative to the Out-paragraph. Effectively, the code stays in the same position, only the Out text is rendered a bit lower.

Fix 'Out:' label position in html output block

---

doc/configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/py_source_parser.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_py_source_parser.py

The in-file comments `# sphinx_gallery_line_numbers` and `# sphinx_gallery_thumbnail_number` are meant to control sphinx gallery behavior. They have any meaning for the reader of the generated example.
This PR introduces the option `remove_config_comments` (default False, corresponding to the current behavior), which allows to remove these comments from the rendered example.
Closes #481.

Add option to remove sphinx_gallery config comments

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py

Closes #491.
It wasn't as simple as just overriding `sys.stderr` (which I did do), I also had to monkey-patch `warnings.showwarning` to use the default implementation, presumably because something else (Sphinx probably?) was overriding it already. This monkey patches it only during code execution, which seems like the right thing to do.
@drammock can you see if this fixes your problem? No config change should be necessary.

MRG, ENH: Catch and write warnings

---

doc/conf.py

Adding the [viewcode](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html) sphinx extension to the docs build of sphinx-gallery will allow users to more easily inspect the sourcecode (when reading the docs and simply clicking on a link)

add link to view sourcecode in docs

---

doc/configuration.rst

see: https://github.com/sphinx-gallery/sphinx-gallery/blob/a69ad570fd175f593b428e8838e54b72211fe1af/sphinx_gallery/binder.py#L216
apparently the 'ref' keyword was used previously ... but it's now called "branch"

fix wrong keyword in docs for "binder"

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

It is easier to create custom scrapers if we have access to the variables in the script.

ENH: Expose example globals

---

doc/conf.py

The warnings happen when using agg backend and using plt.show(). This was taken from scikit-learn. This is related to https://github.com/sphinx-gallery/sphinx-gallery/issues/488. This PR only removes the warnings from our documentation and does not add any documentation from a sphinx-gallery user perspective.
See for example https://sphinx-gallery.github.io/auto_examples/plot_exp.html#sphx-glr-auto-examples-plot-exp-py.

[MRG] Remove matplotlib agg backend + plt.show warnings from doc

---

sphinx_gallery/scrapers.py

@drammock can you see if this fixes https://github.com/mne-tools/mne-python/issues/6634#issuecomment-518774399 for you?
Basically we modify `kwargs` within the loop over figures, which is bad since it means that `kwargs` for figures later down the list can be modified by however we modified them for the preceding ones.

BUG: Fix kwargs modification in loop

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

Closes #528 
Prevents output box if `captured_std.isspace()`.
Test to ensure `execute_code_block` does not generate a code block for `print(__doc__)`.
(also tested locally on [plot_kernal_pca.py](https://scikit-learn.org/dev/auto_examples/decomposition/plot_kernel_pca.html#sphx-glr-auto-examples-decomposition-plot-kernel-pca-py) and does not produce the output box)

[MRG][FIX] Remove output box from print(__doc__)

---

doc/configuration.rst
sphinx_gallery/backreferences.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/_templates/module.rst

When working on #525 I noticed that `make html_dev-noplot` builds for MNE-Python were spending a lot of time in the SG section. I profiled it and there was ~43 sec spent in `generate_gallery_rst` and things that it calls, even though nothing is executed.
Turns out most of this is due to unnecessary `clean_modules` and `_memory_usage` calls -- we only need to call those before actually executing files. I've changed the code to avoid unnecessary calls (i.e., only call them before attempting to actually execute a script). Now `generate_gallery_rst` takes ~3 sec.

ENH: Speed up builds

---

continuous_integration/travis/test_script.sh
doc/configuration.rst
examples/plot_function_identifier.py
sphinx_gallery/backreferences.py
sphinx_gallery/docs_resolv.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/py_source_parser.py
sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_py_source_parser.py
sphinx_gallery/tests/tinybuild/conf.py
sphinx_gallery/tests/tinybuild/examples/future/plot_future_imports.py
sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py

This adds resolution of (most/many) runtime objects using intersphinx. In `master` we only inspected the AST and imports to look for function calls from imported modules. This PR looks at the runtime objects in `globals` to see if they (or their subclasses) are documented somewhere in intersphinx. It greatly increases the number of things in the code snippets that become links. I'll paste a link to an updated example once CircleCI renders so that people can see what I mean.
It's not perfect but it gets us at least some of the way. For example:
1. It does not handle subclasses properly in all cases. ~~For `mne.io.Raw` for example, it properly documents `raw.plot_psd` calls, but does not get `raw.filter` (despite there being documentation for `mne.io.Raw.filter`).~~
2. If objects are …

ENH: Add live object refs and methods

---

doc/_templates/module.rst
doc/configuration.rst
sphinx_gallery/_static/gallery.css
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/tinybuild/_templates/module.rst

Removed inline CSS style from clear <div>
Replaced it with a class with a correspoinding style in gallery.css
This change has been made so the new class can be used in a selector to fix a
bug on the matplotlib website where a tooltip display is cut off by
a related overflow:hidden

add class to clear tag

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

Should fix https://circleci.com/gh/mne-tools/mne-python/16316
@lucyleeow can you look and see if you agree with the change? Basically there is no guarantee that `code_ast.body` is non-empty (it can be empty if a code block contains only comments for example), so we need to protect against it

BUG: Fix index check

---

sphinx_gallery/tests/test_full.py

AppVeyor occasionally has spurious failures, seemingly because Sphinx sometimes gets modification times wrong:
https://ci.appveyor.com/project/sphinx-gallery/sphinx-gallery/builds/28174649/job/ybbpvrd90nrwxbs5
This PR is designed to help fix it. I'll try restarting AppVeyor a few times before merging.

FIX: Fix spurious failures

---

doc/configuration.rst
examples/plot_capture_repr.py

I forgot to update the example gallery for `capture_repr` after we decided to change the default to `capture_repr: ('_repr_html_', '__repr__')`.
Also fixed some typos I made in configuration.

DOC update example capture_repr

---

doc/advanced.rst
sphinx_gallery/gen_rst.py
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_scrapers.py

The goal was just to add a test for #556, but I realized that it (probably) needed `jpg` as a supported format. It was easy enough to add, so I did it, and it should fail with the error reported in #556.
I propose we merge #556, I rebase this, then we merge this.

ENH: Add official JPG support and better tests

---

sphinx_gallery/gen_gallery.py

I tested this with the astropy docs and everything seems to work fine when building in parallel
Fixes https://github.com/sphinx-gallery/sphinx-gallery/issues/560

Mark sphinx extension as parallel-safe for writing

---

.circleci/config.yml
.circleci/docs_deploy.sh
doc/_static/theme_override.css
doc/_templates/layout.html
doc/conf.py
sphinx_gallery/__init__.py

Closes #559.
[EDIT: I manually created] ~~Created~~:
https://sphinx-gallery.github.io/dev/
https://sphinx-gallery.github.io/stable/
Currently just copies of https://sphinx-gallery.github.io/. Steps:
1. Make sure people are happy with how CircleCI renders the version drop-down, then merge this PR
2. Make sure that CircleCI deploys to https://sphinx-gallery.github.io/dev/
3. Release a new version
4. Make sure that CircleCI deploys to https://sphinx-gallery.github.io/stable/ based on the tag
5. Overwrite `https://sphinx-gallery.github.io/index.html` with a URL redirect and remove all other files other than `dev`/`stable` dirs, `index.html`, and `.nojekyll`.

ENH: Add dev/stable distinction

---

.circleci/config.yml
CHANGES.rst
doc/configuration.rst
doc/maintainers.rst
sphinx_gallery/__init__.py

- Updated changelog
- Updated maintainers documentation (there is no `between-tags` parameter for `github_changelog_generator` anymore)
- Added tl;dr note to `configuration.rst` advising how to revert capturing behaviour
Wasn't sure about:
> Update the version in `sphinx_gallery/__init__.py`. It should end in dev0. You should remove this text, and the remaining number will become the version for this release.
I removed the 'dev0'. If this is correct, I will amend this note to:
> Update the version in `sphinx_gallery/__init__.py`, which should end in dev0. You should remove 'dev0', and the remaining number will become the version for this release.

[MRG] Release v0.5.0

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

- wrap the note with a `.. only:: html` directive
- add a test
closes #572

Remove the note link to downloads from pdf output

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

Fixes this bug:
```
File "/home/larsoner/python/sphinx-gallery/sphinx_gallery/gen_rst.py", line 570, in execute_code_block
captured_html = html_header.format(indent(last_repr, u' ' * 8))
File "/usr/lib/python3.8/textwrap.py", line 480, in indent
return ''.join(prefixed_lines())
File "/usr/lib/python3.8/textwrap.py", line 478, in prefixed_lines
for line in text.splitlines(True):
AttributeError: 'NoneType' object has no attribute 'splitlines'
Exception occurred:
File "/usr/lib/python3.8/textwrap.py", line 478, in prefixed_lines
for line in text.splitlines(True):
AttributeError: 'NoneType' object has no attribute 'splitlines'
```
Will merge once CIs are happy since this seems like a pretty clear bug, and it's going to hold up using `_repr_html_` in MNE.
@lucyleeow feel free to take a quick …

BUG: Fix repr None

---

doc/advanced.rst

Limiting code duplication makes documentation more robust, so I added an example of `literalinclude` in the doc, I hope this is the right place.

mention literalinclude in the doc

---

doc/_static/theme_override.css
doc/configuration.rst
sphinx_gallery/_static/gallery.css
sphinx_gallery/backreferences.py
sphinx_gallery/docs_resolv.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py

Adds classes for `sphx-glr-backref-*` (see updated configuration page) and sets the default CSS to:
```
a.sphx-glr-backref-instance {
text-decoration: none;
}
```
Closes #580

ENH: Add CSS classes for backrefs

---

sphinx_gallery/backreferences.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py

closes #583 
If an example uses a function like this:
```
import h.i
h.i.j()
```
[`get_mapping`](https://github.com/sphinx-gallery/sphinx-gallery/blob/44ed8000930a8b8cea70dcfda40a799750edee7d/sphinx_gallery/backreferences.py#L62) will check if `local_name`, in this case `h`, is in the `self.imported_names` dict. The key for this import would be `h.i` so it doesn't match.
I've added a for loop which will run for 'n' times, where 'n' is the max number of splits (`split('.')`) of all keys in `self.imported_names`. In each loop another split of the locally used name is added onto `local_name` which is checked to see if it exists in `self.imported_names`. e.g., for the above example the loop would run twice, first time `local_name` would be `h` and second time `local_name` would be `h.i`.
Not …

[MRG] Fix backreferences for functions not directly imported

---

doc/reference.rst

I just started looking at this project today and noticed that `docs_resolv` is in the API Reference list twice.  This is just a 1-line PR to remove the second entry.

Remove duplicate doc_solver entry in the API reference structure

---

sphinx_gallery/docs_resolv.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_gallery.py

So far just takes care of the first part of #587.
I plan to tackle the other problems, too, but this is a separable first step so this is ready for review/merge from my end @lucyleeow 
The change to `test_gen_gallery` was necessary because my computer username (`larsoner`) has `one` in it, so the regex was errantly matching paths it wasn't meant to. Using `basename` to get the filenames themselves fixes it.

MRG, FIX: Fix backref styling

---

sphinx_gallery/_static/gallery.css

closes #544 
Added CSS for pandas df, copied from nbsphinx (suggested here: https://github.com/sphinx-gallery/sphinx-gallery/issues/544#issuecomment-539992747).
I can include a border:
Or remove the black border:
The latter makes it look exactly like in jupyter notebook:
Note that rows become highlighted in light blue on hover, just like in notebooks.

[MRG] [ENH] Add css for pandas df

---

sphinx_gallery/_static/gallery.css

When using an SVG plot in "portrait" mode (i.e. height larger than width), the thumbnail can collide with the title text.
It looks like SVG thumbnails are currently assumed to be in "landscape" mode, this PR avoids this assumption.
I'm not very good at CSS, so this is very likely to have unintended side effects!

CSS: Restrict thumbnail height to 112 px

---

sphinx_gallery/backreferences.py
sphinx_gallery/docs_resolv.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py

Link to methods and properties properly (part of #587).
Locally I can confirm that building MNE docs now produces links to things like `ica.plot_properties`, which is great.

MRG, ENH: Link to methods and properties properly

---

doc/advanced.rst
sphinx_gallery/load_style.py
sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_load_style.py

As discussed in https://github.com/sphinx-gallery/sphinx-gallery/pull/599#issuecomment-576200916, this enables following usage in `conf.py`:
```python
extensions = [
'sphinx_gallery.load_style',
]
```
... which only loads the CSS style and sets the corresponding static directory. Nothing else.
For now, this provides a minimal solution without any configuration options.
@larsoner suggested in https://github.com/sphinx-gallery/sphinx-gallery/pull/599#issuecomment-576750591 to add configurability:
> Even in the case where you want to load SG style(s), we'd still want a way to say which styles to load.
I think we don't need that yet, because for now there aren't even multiple styles, there's only one.
I think configurability can be added later (when needed), an example for a possible …

MRG, ENH: Provide sub-extension sphinx_gallery.load_style

---

sphinx_gallery/gen_rst.py

On macOS with `memory_profiler` during builds I frequently get:
```
File "/Users/larsoner/python/sphinx-gallery/sphinx_gallery/gen_rst.py", line 469, in _get_memory_base
memories = memory_usage(proc, interval=1e-3, timeout=timeout)
File "/Users/larsoner/anaconda3/lib/python3.7/site-packages/memory_profiler.py", line 371, in memory_usage
include_children=include_children)
...
File "/Users/larsoner/anaconda3/lib/python3.7/site-packages/psutil/_psosx.py", line 363, in catch_zombie
raise ZombieProcess(proc.pid, proc._name, proc._ppid)
psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=62842)
Exception occurred:
File "/Users/larsoner/anaconda3/lib/python3.7/site-packages/psutil/_psosx.py", line 363, in catch_zombie
raise ZombieProcess(proc.pid, proc._name, …
```

BUG: Longer timeout on macOS

---

doc/configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_gen_gallery.py

closes #635 
(I didn't know how to parameterize `test_backreferences_dir_pathlib_config` with `test_backreferences_dir_config` but maybe that would have been overboard)

ENH Allow backrefences_dir to be pathlib object

---

README.rst

Seems to be working:
https://zenodo.org/account/settings/github/repository/sphinx-gallery/sphinx-gallery
So let's add their recommended badge to our set of badges. The link isn't active yet but I assume this will take some time (hours).

MRG, ENH: Add Zenodo badge

---

doc/advanced.rst
doc/configuration.rst
doc/maintainers.rst

As I was using the documentation I noticed a couple typos, so I figured I would fix them. 
Updates are some typo fixes for rst files in /doc.

DOC: Fix typos in documentation files.

---

doc/advanced.rst

The `PNGScraper` example has some syntax errors that are fixed here. Also, the searched `pngs` should be checked within `path_current_example` instead of `os.getcwd()` for most use-cases.

DOC: Fix PNGScraper example

---

.circleci/config.yml

While working on #656 I noticed some cruft in our CircleCI build. This bumps to 3.7, as we can't do 3.8 until VTK9 comes out, and then Mayavi cuts a release. It also removes the PyQt5 restriction because you just need to install some system libs to get around the libxcb problems.

MAINT: Update CircleCI

---

doc/syntax.rst

Update links to code block separator (`# %%`) documentation of various editors/IDEs.
Minor change to wording.

DOC Update links in syntax.rst

---

examples/plot_1_exp.py
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_scrapers.py
sphinx_gallery/tests/tinybuild/examples/plot_matplotlib_alt.py

closes #538 
For matplotlib figures, checks for 'suptitle', then tries `get_title()` for all axes of a figure.
If no text found, uses the file name. File name also used by default, for all non-matplotlib figures.
Currently only works for single figures. Will rework `matplotlib_scraper` so `figure_rst` is run on every loop so it works for 'HLIST_IMAGE_TEMPLATE'. Suggestions welcome
cc @ogrisel

ENH More informative 'alt' attribute for images

---

examples/plot_1_exp.py
sphinx_gallery/scrapers.py
sphinx_gallery/tests/tinybuild/examples/plot_matplotlib_alt.py

In MNE I have been getting cryptic errors:
https://app.circleci.com/pipelines/github/mne-tools/mne-python/1345/workflows/3cb34706-7fa5-473a-8b57-376bd238c024/jobs/19753/steps
Examining the RST shows:
```
.. rst-class:: sphx-glr-horizontal
*
.. image:: /auto_examples/decoding/images/sphx_glr_plot_receptive_field_mtrf_003.png
:alt: Mean Model
Coefficients
:class: sphx-glr-multi-img
```

FIX: Remove newlines from title

---

doc/configuration.rst

closes #606
Using the adaptation of the catch-all target of sphinx quick-start, suggested by @prisae also works and I'm happy to amend to that if more appropriate.

DOC Update html-noplot

---

doc/conf.py

Update to https:
> intersphinx inventory has moved: http://www.sphinx-doc.org/en/stable/objects.inv -> https://www.sphinx-doc.org/en/stable/objects.inv

DOC Update Sphinx url to https

---

doc/syntax.rst

Nitpicks in `syntax.rst`. Clarify section header underlining (mentioned in #342).

DOC Clarify syntax.rst

---

sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/examples/plot_svg.py

Add punctuation to title of `plot_svg.py` in tinybuild to test thumbnail alt attribute.

Better alt thumbnail test for punctuation in title

---

doc/_templates/module.rst
doc/configuration.rst
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/_templates/module.rst
sphinx_gallery/tests/tinybuild/index.rst

closes #496 
Add cross referencing label to `module.rst` to easily link to mini-galleries of module fun/classes.
Add test in tinybuild

ENH Add cross ref label to template module.rst

---

sphinx_gallery/gen_gallery.py

Fix lint:
```
sphinx_gallery/gen_gallery.py:423:47: E741 ambiguous variable name 'l'
sphinx_gallery/gen_gallery.py:441:51: E741 ambiguous variable name 'l'
```

Fix lint in gen_gallery.py

---

sphinx_gallery/backreferences.py
sphinx_gallery/tests/test_backreferences.py

The regular expression used to find backreferences in docstrings doesn't currently skip any leading tilde.  For example, the following wasn't getting included for the backreference because `~numpy` was interpreted as the module:
```
:func:`~numpy.exp`
```
This PR fixes the regular expression.

Fixed backreference inspection to account for tilde use

---

doc/_templates/module.rst
doc/configuration.rst
doc/reference.rst
sphinx_gallery/backreferences.py
sphinx_gallery/directives.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/_templates/module.rst
sphinx_gallery/tests/tinybuild/minigallery.rst

Per #683, here's what I have in mind for the API for the proposed `minigallery` Sphinx directive to easily insert mini-galleries.  My conception is that the new approach would entirely replace the old approach in the user documentation, but the old approach would still work.
Once there's agreement on the API, I'll code the directive, with [this implementation](https://github.com/ayshih/sunpy/blob/c7f8cb2776acb21a9029e943c868503772740b2b/docs/conf.py#L320) as the starting point.

Sphinx directive to insert mini-galleries

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/tinybuild/examples/plot_log.py

This restructures our patching of `sys.stdout`/`stderr` to occur on a per-script basis, with some gymnastics to deal with our testing infrastructure calling things like `execute_code_block` outside a standard context where `with _LoggingTee` would otherwise have already set `sys.stdout`.
Closes #672.
@pmeier can you see if this fixes things for you?

FIX: Fix sys.stdout patching

---

.circleci/config.yml
.travis.yml
README.rst
doc/conf.py
doc/configuration.rst
doc/reference.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/conf.py
sphinx_gallery/utils.py

With this we ~~automatically~~ use `optipng` if it's available EDIT: and the user requests it, and emit a `logger.warning` if it's not.
Intentionally installed on some CI runs but not others to ensure we don't break things for people. @GaelVaroquaux WDYT?
Closes #655

ENH: Use optipng when requested

---

sphinx_gallery/backreferences.py
sphinx_gallery/binder.py
sphinx_gallery/docs_resolv.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/py_source_parser.py
sphinx_gallery/scrapers.py
sphinx_gallery/sorting.py
sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_binder.py
sphinx_gallery/tests/test_docs_resolv.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_py_source_parser.py
sphinx_gallery/tests/test_scrapers.py
sphinx_gallery/tests/test_sorting.py
sphinx_gallery/utils.py

Use Sphinx errors rather than built-in ones when something goes wrong. This coupled with https://github.com/sphinx-doc/sphinx/pull/7699 should make sphinx dev work again. Should probably wait for that one to be merged before merging this one, hence the WIP label.
Closes #600

ENH: Use Sphinx errors

---

.circleci/config.yml
doc/configuration.rst
sphinx_gallery/scrapers.py

Matplotlib also has `ArtistAnimation`. It would be nice to have this for matplotlib (https://github.com/matplotlib/matplotlib/pull/17477), maybe in a 0.7.1 release sometime? Let's wait to see what else breaks in the meantime before cutting one, though.

ENH: Use broader def of Animation

---

sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_full.py

closes #694
Did not realise it would be that simple, seems magical.
I didn't add anything to doc assuming no one would miss this warning.

Remove matplotlib agg warning

---

.circleci/config.yml

PyQt went to 5.15 IIRC, which I think is causing us some library problems. Let's see if this fixes them.
Python Nightly is broken on Travis, but we might just be able to wait that one out.

MAINT: Fix CircleCI

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

Per comment: https://github.com/readthedocs/readthedocs.org/issues/4765#issuecomment-431927720
I was able to test this by monkey patching the change, and confirm that HTML now renders both on local build and on Read the Docs.

Enable html to be rendered on readthedocs

---

doc/configuration.rst

Add ref label and update example since we remove the matplotlib warning by default.

DOC Update warning section in configuration.rst

---

sphinx_gallery/gen_gallery.py

I realise I did not check these configs when I added them.
Adds checks that these are the correct type and value.

BUG Check 'capture_repr' and 'ignore_repr_types'

---

sphinx_gallery/downloads.py
sphinx_gallery/gen_gallery.py

Closes #704, Cc @larsoner
The zip files comprising all examples were included with absolute file links. If one wants to use galleries built on another machine this results in an error if the paths do not match.

BUG: Use relative paths for zip downloads

---

sphinx_gallery/docs_resolv.py

I was doing a `make html_dev-noplot` run and I was confused why links weren't showing up in the code. There isn't really a good reason not to put them in nowadays since we use `intersphinx` to find names and such. It's quick relative to the entire build time, and useful even in noplot runs.
Hopefully the "inexplicable fix" workaround is no longer needed. If it causes problems, we should fix the underlying bug.

BUG: Always do linking

---

examples/plot_8_animations.py

I thought it would be useful to specify 'Maplotlib' in the animation example, especially if we will add a plotly example (#715).

DOC Specify matplotlib in animation example

---

sphinx_gallery/notebook.py
sphinx_gallery/tests/test_notebook.py

This enables support for converting headings from RST into Markdown text for Jupyter Notebooks, with heading levels maintained for entire notebook.

Support headings in RST to MD

---

sphinx_gallery/backreferences.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/utils.py

Currently md5 hash for Python files depends on what platform file is on, as file endings will differ. This change reads the Python files in the hashing function with universal line endings, such md5 is independent of platform being used.
Surrogate escapes are used, to ensure that it can handle any errors without data loss.
This is useful when adding a complex or long running examples into a repository that may be used across platforms.

Make md5 hash independent of platform line endings

---

doc/configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/notebook.py
sphinx_gallery/tests/test_notebook.py

Currently, when notebooks are generated, the links to images found in rST remain unmodified, meaning images expected to be either local or found on web server hosting documentation are broken.
This change allows inclusion of images via data URIs, or prefixing the image links in the notebooks, for example to server hosting documentation.
This also changes the markdown output to use HTML `img` tag, and such also supports the width and height options.

Add support for image links and data URIs for notebooks

---

doc/advanced.rst

This PR adds a sentence to the documentation of Example 2 for custom image scraper to make it clearer and prevent misunderstandings like the one documented in #728 .

Improve documentation of example for custom image scraper

---

appveyor.yml
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

Prevent users from having their builds hang because of `input()` calls. Instead of getting a hang, they now get:
```
Extension error:
Here is a summary of the problems encountered when running the examples
Unexpected failing examples:
/home/larsoner/python/sphinx-gallery/sphinx_gallery/tests/tinybuild/examples/plot_animation.py failed leaving traceback:
Traceback (most recent call last):
File "/home/larsoner/python/sphinx-gallery/sphinx_gallery/tests/tinybuild/examples/plot_animation.py", line 15, in <module>
input()
sphinx.errors.ExtensionError: Cannot use input() builtin function in Sphinx-gallery examples
```
Note that I added a bit of code to `_handle_exception` to trim these unhelpful lines from the traceback we print:
```
File …
```

ENH: Dont allow input

---

sphinx_gallery/scrapers.py

Since ffmpeg GIF writing was fixed in matplotlib/matplotlib#18093, which will be included in matplotlib 3.3.1, enable using that for capturing animations (when running a recent enough version).

Enable ffmpeg for animations for newer matplotlib

---

doc/configuration.rst
examples/plot_7_sys_argv.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/conf.py
sphinx_gallery/tests/tinybuild/examples/plot_command_line_args.py

This PR implements an option to pass command line args to example scripts. It closely follows the suggestion by @larsoner made in #731 :
- I added a `reset_argv` option to the configuration which needs to be a callable that accepts `gallery_conf` and `script_vars` as input arguments and return a list of strings which will be the additional `sys.argv` (in addition to the src_file itself).
- As a default value, I set `reset_argv` to be a callable that just returns an empty list, which is equivalent to the current behavior.
- I also added documentation of this option.
The PR is missing a test for this function. I was not sure how to add a test for this and would need some advice since I'm not familiar with the test suite.

Implement option to pass command line args to example scripts

---

sphinx_gallery/gen_rst.py
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/Makefile
sphinx_gallery/tests/tinybuild/conf.py
sphinx_gallery/tests/tinybuild/examples/plot_scraper_broken.py

If a scraper hits an error, the traceback is pretty worthless, [for example](https://app.circleci.com/pipelines/github/mne-tools/mne-nirs/441/workflows/dc50c665-0471-4305-9043-d0f7f2e0d7e0/jobs/444):
```
generating gallery for auto_examples... [ 60%] plot_10_hrf.py
Extension error:
Handler <function generate_gallery_rst at 0x7fe6548b0e50> for event 'builder-inited' threw an exception (exception: zero-size array to reduction operation minimum which has no identity)
make: *** [Makefile:60: html] Error 2
```
With this PR it's handled like any other script error (from our new test):
```
...
loading intersphinx inventory from https://joblib.readthedocs.io/en/latest/objects.inv...
generating gallery...
/Users/larsoner/python/sphinx-gallery/sphinx_gallery/tests/tinybuild/examples/plot_scraper_bro …
```

BUG: Fix handling of scraper error

---

sphinx_gallery/gen_gallery.py

I realised even when `'pypandoc': False` logger outputs:
```
Using pandoc version: None to convert rst text blocks to markdown for .ipynb files
```
Added a message for when `'pypandoc': False` but happy to change to `else: pass` have no message

Fix logger message pypandoc

---

doc/getting_started.rst
doc/syntax.rst
examples/plot_0_sin.py

Add link to `syntax.rst` to the explanation on how to reference other examples.
Some other doc nitpicks

DOC Add link to cross referencing example

---

sphinx_gallery/scrapers.py

This removes the `only` directive, leaving `raw` directive to allow builder to decide how/if to render raw HTML.
This is similar to issue in #700

Enable animations HTML to be rendered on readthedocs

---

.circleci/config.yml
appveyor.yml
continuous_integration/travis/install.sh
dev-requirements.txt
doc/configuration.rst
examples/plot_3_capture_repr.py
setup.py
sphinx_gallery/_static/gallery-rendered-html.css
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/tinybuild/examples/plot_repr.py

I dug into the Jupyter notebook default formatting a bit, and this allows us to hopefully style our HTML outputs similarly to theirs. See for example:
https://github.com/mne-tools/mne-nirs/pull/167#issuecomment-698277516
On my machine on this PR I now get:

ENH: Style HTML output like jupyter

---

doc/projects_list.rst

closes #753
Ideally when you are in the dev version of the docs, this link should be https://sphinx-gallery.github.io/dev/auto_examples/index.html, but I am not sure how to make this link change depending on the doc version...any ideas @larsoner ? It's also not that important and I am sure we can leave as stable.

DOC update link in projects_list

---

.travis.yml
doc/configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py

Makes it much easier to have a Makefile target to force re-running of a specific example/examples. See extended explanation in `configuration.rst`.

ENH: Add run_stale_examples config var

---

doc/configuration.rst

I might have gotten this wrong as I am not familiar with SPHINXOPTS syntax but removed backticks and added space after `-D`

DOC Amend run_stale_examples command in configuration.rst

---

sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_scrapers.py
sphinx_gallery/tests/tinybuild/conf.py

Closes #774.
Also removes `mod_example_dir` -- we deprecated it 3 years ago, should be safe to remove.

ENH, DEP: Check for invalid keys, remove ancient key

---

doc/configuration.rst

I noticed this link points to python 2; I've updated it so it will now point to python 3.

Point to up-to-date re documentation

---

sphinx_gallery/utils.py

Rescaling the images down to thumbnails often results in image borders that are white. Changing the alpha value here modifies these borders to be transparent, so that any border areas from the rescaling take on the background color of the thumbnail. This is an enhancement for users who want to use custom thumbnail background colors.

Make any borders introduced when rescaling images to thumbnails transparent

---

README.rst

Reference changes in 0ea6202195845b89f02b49055d4227fcd89ec380, moving from travis CI to Azure

Replace Travis CI badge with Azure Badge in README

---

doc/configuration.rst
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/tinybuild/examples/plot_matplotlib_alt.py

- Let sphinx_gallery_thumbnail_number support negative index
- Add an example with a negative index
Fixes #785.

Let sphinx_gallery_thumbnail_number support negative indexes

---

doc/configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_gen_gallery.py

With this configuration option set sphinx will only exit with a non-zero code if the -W flag is set.
I would find this useful on sunpy's CI because then sphinx-gallery will respect the fact that some of our builds have -W set and some (ones where we want to generate previews) don't.
Fixes #789

Add a configuration to warn on error not fail

---

doc/advanced.rst
doc/configuration.rst
sphinx_gallery/gen_rst.py
sphinx_gallery/py_source_parser.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_py_source_parser.py
sphinx_gallery/tests/tinybuild/examples/plot_defer_figures.py

Closes #363
This PR adds an optional flag for a code block to defer figure scraping to the next code block.  If the code-block executor sees the comment `# sphinx_gallery_defer_figures`, it will not run `save_figures()` to scrape figures, and any figures are left open for the next code block.  Thus, it becomes possible to interleave text blocks between multiple code blocks of plotting commands, with no figures being shown until after the desired code block.
The flag gets stripped out along with the usual config comments (e.g., `# sphinx_gallery_thumbnail_number = N`).
Here's a rendered example:
where the first code block is:
```python
plt.plot([1,2,3,4,5])
plt.plot([5,4,3,2,1])
```
This needs documentation and tests, of course, but I wanted feedback first.

Optional flag to defer figure scraping to the next code block

---

sphinx_gallery/gen_rst.py

In gen_rst.save_thumbnail() the file extension is from file_conf is
always used, regardless of the value of 'default_thumb_file'.  If
'default_thumb_file' is .svg (or .gif) it is still passed to pillow,
which does not handle them properly.

Fix SVG default thumbnail support

---

doc/advanced.rst

I think the `SOURCEDIR` variable is missing from the suggested Makefile in the docs. Running it as-is was raising an error for me:
```
usage: sphinx-build [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]
sphinx-build: error: the following arguments are required: outputdir, filenames
```

DOC Include SOURCEDIR in Makefile

---

doc/configuration.rst
sphinx_gallery/directives.py

Closes https://github.com/sphinx-gallery/sphinx-gallery/issues/812
This PR avoids showing the minigallery if there's no example using the object. It's probably too hacky for inclusion as-is but I'm not sure how to best proceed, so I'd be happy to address any feeback :)

ENH: Only add minigallery if there's something to show

---

doc/conf.py
doc/configuration.rst
sphinx_gallery/directives.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_scrapers.py
sphinx_gallery/tests/tinybuild/conf.py

Right now, at least at Matplotlib.org, all images are 100 dpi, and 200 dpi images look bad on hi-dpi monitors.  We could save 200 dpi and scale, but that was deemed problematic.  The "proper" solution is to serve images with the `srcset` option and let the client browser decide what to download: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
This PR implements this for the matplotlib scraper.  Of course this requires a new directive as well.  
The PR adds a `image_srcset=["", "2x"]` configuration option that causes the matplotlib scraper to save two (or more) files, the usual image, and a dpi=200 (or other dpi, i.e. `image_srcset=["", "2x", "3x"]`) version that gets named `filename_2_0.png`.  It then adds a new directive to the gallery rst: …

ENH: add hidpi option to matplotlib_scraper and directive

---

.circleci/config.yml

Install tex-gyre in circleCI.
Other CI failures are separate problems (will tackle in separate PR).

BUG Fix LaTeX Error: File `tgtermes.sty' not found in CI

---

continuous_integration/azure/install.sh

Fix
> ../../../.local/lib/python3.10/site-packages/jinja2/__init__.py:6: in <module>
from markupsafe import escape
/usr/lib/python3/dist-packages/markupsafe/__init__.py:13: in <module>
from collections import Mapping
E   ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
I think this is fixed here: https://github.com/pallets/markupsafe/commit/86d4146f0debc004b4a8b6aa69df818ef4ad9080
Pin markupsafe to version >=1.1
(Previously we had to pin jinja2 due to same eror, I wonder if adding all these pins is robust/a good fix?)

Bug Pin markupsafe version in Python nightly

---

sphinx_gallery/tests/test_full.py

Parameterise test_minigallery_directive to make debugging easier.
Fix `test_minigallery_directive` failing in Windows. HTML output in Windows has more (new) lines, so had to make `nlines` bigger to capture some sections completely. It should not interfer with the linux html output as have only increased `nlines` by 1-3, and this should max only capture the test name part of the next section, e.g.:
```html
</div>
</div><div class="sphx-glr-clear"></div><p>Test 2-D-D</p>
</div>
```
and not capture the heading lines.

BUG Fix test_minigallery_directive failing on Windows

---

doc/configuration.rst
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_full_noexec.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/tinybuild/examples/plot_repr.py

closes #751
It is possible for this configuration to work only when the gallery is NOT executable (e.g., when plot_gallery is False) but this complicates the code and makes testing (using tinybuild) difficult, and possibly unnecessarily restrains the config function. I have left it as always creating dummy images. The images are created after executing the code block (so after any 'real' figures are saved) - thus would not overwrite any generated 'real' figures. Open to changing.
TODO
Still need to add documentation.
Should amend to test in example that generates images, to ensure no real images are overwritten

ENH Add config that generates dummy images to prevent missing image warnings

---

CHANGES.rst
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

See the problem in the output block in https://braindecode.org/auto_examples/plot_sleep_staging.html#training
See all the `[36m` which are otherwise used to get colors in the terminal.
With this fix it looks much better !
cc @robintibor

Sanitize ANSI characters from generated RST

---

examples/plot_8_animations.py

When looking at how to enable animations in sphinx gallery, this example was the first thing I came upon. I thought it would be helpful to indicate how to enable support here in the example, so users don't have to go looking in the Configuration page.

Add info on enabling animation support to example

---

.circleci/config.yml
azure-pipelines.yml
continuous_integration/azure/install.sh
doc/advanced.rst
doc/conf.py
doc/configuration.rst
setup.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/tinybuild/conf.py

As noted in #866, `reset_modules` functions are currently only called _before_ examples are run.  In the case that the last example modifies an import, `reset_modules` won't run subsequent to this example.  The modified module will leak out into other parts of the build process.
This PR adds another configuration option `reset_modules_order` that can be `after`, `before`, or `both`, which specifies when the callables in `reset_modules` are called.  The default is `before` which retains the current behavior.
This PR closes #866.

Enable `reset_modules` to run either before or after examples, or both

---

doc/configuration.rst
sphinx_gallery/_static/sg_gallery.css

Follow up to #484, which got misaligned again, likely through pydata-sphinx-theme.
Note: This is a purely empirical suggestion based on the matplotlib docs, e.g.:
https://matplotlib.org/devdocs/tutorials/colors/colormap-manipulation.html
I don't know how to find out whether this is generally ok.
Before:
After:

Fix "Out" layout for pydata-sphinx-theme

---

doc/configuration.rst
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_scrapers.py

Reset the units registry to its default contents by reloading all submodules that (currently, as of mpl 3.5.0) populate the registry.
Closes #889.
For further background information on reloading modules see https://stackoverflow.com/a/487718/3944322 and [this gist](https://gist.github.com/StefRe/f92b13c85cfd7cc294fa8a4b4610331f).

Fix matplotlib resetter _reset_matplotlib

---

doc/configuration.rst
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

Make `gallery_conf['capture_repr']` overridable by `# sphinx_gallery_capture_repr` file config comment.
Use case: Sometimes, especially in examples with many short code sections, it is undesirable to have all the output boxes while you can't globally set `capture_repr` to `()` as there are some examples in the gallery where the output is needed. Making all these short code sections end with `plt.show()` or turning the last line into an assignment isn't ideal either as the former introduces a lot of extra lines of code and the latter may seem confusing, see matplotlib/matplotlib#21794 (putting a semicolon after the last expression doesn't work here as the code is first compiled into an AST and then the last expression is taken from the tree where the semicolon as code delimiter isn't …

Config capture_repr on file-by-file basis

---

sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_gen_rst.py

The class-based test was making things a pain, let's just use standard functions and fixtures.
Diff looks worse than necessary because of the indentation change, but not that much actually changed.
Closes #893

FIX: Fix for latest pytest

---

doc/configuration.rst
sphinx_gallery/backreferences.py

Update docs for Adding mini-galleries for API documentation so that documentation corresponds to actual code.
Closes #897.

DOC Update docs for Adding mini-galleries for API documentation

---

CHANGES.rst
sphinx_gallery/_static/sg_gallery.css
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

There's still an arbitrary padding, but now it goes on the added content instead of the existing `pre`. Without the negative margin, this prevents the `pre` from accidentally overlapping previous content. Some additional tweaks are necessary to work with the pydata sphinx theme, but it appears to work for the rtd theme as well.
For example, the error output [on this page](https://65575-1385122-gh.circle-artifacts.com/0/doc/build/html/gallery/style_sheets/style_sheets_reference.html) uses the same class, but is oddly placed due to the negative margins.
On the plot strings example (i.e., using rtd theme), this looks like this (at 500%):
and here's how it looks in a Matplotlib example (i.e., using mpl-sphinx-theme, which derives from pydata-sphinx-theme):
It's a tiny bit too low, but that's …

Use pseudo-elements for 'Out:' prefixing

---

doc/conf.py

to avoid redirection to current documentation

Fix matplotlib intersphinx url

---

sphinx_gallery/gen_rst.py

When running `reset_modules` in the `after` case, we need to `del script_vars, global_vars` in order to ensure a `gc.collect()` that follows will actually be able to collect the variables from the script that ran. A bit of a corner case, but it's easy to implement and hard to test, so I think this is probably good enough as is.
Okay for you @lucyleeow ?

MAINT: Clean up namespace

---

.gitignore
doc/configuration.rst
sphinx_gallery/backreferences.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/tinybuild/conf.py
sphinx_gallery/tests/tinybuild/examples/plot_second_future_imports.py
sphinx_gallery/tests/tinybuild/index.rst

New configuration key 'exclude_implicit_doc' to prevent generation of
backreferences for the names given in this key. This only affects
implicite backreferences, i.e. names extracted from the code. Explicit
backreferences given the sphinx directives are not affected.
Closes #898.
I tried my best to write a readable and concise documentation section but this should certainly streamlined a bit by native speakers.

Possibility to exclude implicit backreferences

---

examples/no_output/README.txt
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/examples/future/README.rst

Fixes #855.
Let's assume the gallery structure is the following (note the new `readme.rst` files in each subsection):
```
- top_level
- readme.rst
- subdir
- readme.rst
- example.rst
- example2.rst
- subdir2
- readme.rst
- example1.rst
- example2.rst
```
This PR:
- generates an `index.rst` file for each subsection; it contains `readme.rst`, the gallery items, and a hidden toctree of the gallery items
- includes each subsection's index file in a hidden toctree appended at the end of the main sections index file
On-going tasks:

[WIP] Handle nested structures

---

CHANGES.rst

DOC: fix rst link syntax in changelog

---

azure-pipelines.yml

Hopefully fix failures seen in https://github.com/sphinx-gallery/sphinx-gallery/pull/930 by combining the problematic job with another one (seems okay to do here)

MAINT: Fix CIs

---

continuous_integration/azure/install.sh
sphinx_gallery/utils.py

Fixes warnings of the form:
```
/home/circleci/python_env/lib/python3.8/site-packages/sphinx_gallery/utils.py:64: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
img = img.resize((width_sc, height_sc), Image.BICUBIC)
```
Will merge once it comes back green to avoid these warnings

FIX: Fix for dep

---

README.rst

[Apache TVM](https://tvm.apache.org/) is an open source machine learning compiler framework that's able to compile neural networks for a variety of backends, including CPUs, GPUs, accelerators, and microcontrollers. We use Sphinx-Gallery for our [how-to tutorials page](https://tvm.apache.org/docs/how_to/index.html), and it works well.
Would be cool to add it to the project list!

Add Apache TVM to user projects list

---

sphinx_gallery/notebook.py
sphinx_gallery/tests/test_notebook.py

Currently, embedded URIs do not render correctly when converted to `.ipynb` notebooks. Here's one example of the `.ipynb` you can download from the [Executing a Tiny Model with TVMC Micro]:(https://tvm.apache.org/docs/how_to/work_with_microtvm/micro_tvmc.html#sphx-glr-how-to-work-with-microtvm-micro-tvmc-py)
The fix for this is pretty straightforward, and just involves using a Regex to find and replace these with the Markdown format of links. Should be a pretty straightforward suggestion!

Fix rendering of embedded URIs in Python notebooks

---

sphinx_gallery/backreferences.py

Closes #945.
Simply modify the DOM so that examples featuring a given API reference have the correct common parent (same as minigalleries).

Store API reference examples thumbnails in common div

---

sphinx_gallery/_static/sg_gallery-dataframe.css
sphinx_gallery/_static/sg_gallery-rendered-html.css
sphinx_gallery/_static/sg_gallery.css

Following https://github.com/pydata/pydata-sphinx-theme/pull/629 users of pydata-sphinx-theme (so far) can opt in to having dark mode. This just makes SG's CSS compatible with `data-theme="dark"` mode. It does this by using CSS variables, which I think is helpful for customization and understanding the colors that actually get used.
| Before | After |
| -- | -- |
| ![Screenshot from 2022-04-20 11-17-17](https://user-images.githubusercontent.com/2365790/164265377-ecd70a58-beb2-4b87-ae3e-d03a54b63444.png) | ![Screenshot from 2022-04-20 11-17-54](https://user-images.githubusercontent.com/2365790/164265398-c86480a9-969e-4010-9ae2-e2c04c7eee36.png) |
| ![Screenshot from 2022-04-20 11-38-52](https://user-images.githubusercontent.com/2365790/164270098-c4174382-741c-43bc-b26b-67944e915a4d.png) | …

ENH: Better dark mode support

---

doc/configuration.rst
sphinx_gallery/gen_rst.py
sphinx_gallery/py_source_parser.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_py_source_parser.py

This PR adds the flags `# sphinx_gallery_start_ignore` and `# sphinx_gallery_end_ignore`, which can be used in Python source files. For example, consider the following snippet of a source Python file:
```python
#
import subprocess
from unittest.mock import create_autospec, MagicMock
subprocess.run = create_autospec(subprocess.run, return_value="nano33ble\n")
arduino_board = subprocess.run(
["arduino-cli", "board", "list], check=True, stdout=subprocess.PIPE
)
```
In this example, the code between `start_ignore` and `end_ignore` **will** be run when the `.py` file is executed. However, when an HTML page is built from the `.py` script, those flags and the lines between them will be ignored. Hence the code block as seen from the webpage would look like this:
```python
import subprocess …
```

Add flag to ignore code blocks in Python source parser

---

doc/conf.py
doc/configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/notebook.py
sphinx_gallery/tests/reference_parse.txt
sphinx_gallery/tests/test_notebook.py
tutorials/plot_parse.py

This pull request improves the way `notebook.py` creates Jupyter notebooks by introducing two changes. First, when generating code blocks in Markdown, we now use the ```[language] format instead of indenting. This causes one-line code blocks to render correctly, and also makes syntax highlighting work correctly. For example, consider the lines:
```
.. code-block:: bash
flatc --version
```
Many Jupyter notebook editors (like [Google Colab](https://colab.research.google.com/) do not render this as code as all! With this change, it would instead be translated like the following, which both renders correctly and has syntax highlighting:
````
```bash
flatc --version
```
````
Additionally, this PR makes `notebook.py` recognize so-called [Jupyter magic …
```

Improve Jupyter notebook converter's handling of code blocks

---

examples/plot_seaborn_import_1.py
examples/plot_seaborn_import_2.py

Follow-up of #969. I added test examples to trigger the warnings and test the fix, but forgot to say that they needed to be removed before the PR is merged.
This PR removes the test examples.

Remove test examples for seaborn warning

---

sphinx_gallery/_static/sg_gallery.css

cc @alexisthual none of the examples here are clickable, this seems to fix it. Do you agree it's the right fix?
https://sphinx-gallery.github.io/dev/auto_examples/index.html

BUG: Fix bug with clicking examples

---

CHANGES.rst
doc/maintainers.rst
sphinx_gallery/__init__.py

Closes #965
Following https://sphinx-gallery.github.io/dev/maintainers.html#prepare-for-release

MAINT: Bump to 0.11.0

---

sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_py_source_parser.py
sphinx_gallery/utils.py

No need to re-implement things in the standard library, meaning less code to worry about here.
Note, this is based on #985 because it removes the side-effect that the `fakesphinxapp` fixture was really for.

Use Mock more in tests

---

sphinx_gallery/gen_gallery.py

I wrote a quick function to just basically grep the example files for matches with the functions/classes/methods. There was an issue with methods in particular not being found because they are called from a variable name e.g. (`brain = mne.viz.Brain(...)` `brain.add_skull(...)`) how the example matching is done currently. Searching for just the function/class/method e.g. `add_skull` could be a false-positive because other modules have the same functions/classes/methods. The ubiquitous `fit(...)` comes to mind as something that would cause the method in this PR real trouble with false-positives. However, if you've seen one `fit`, you've kind of seen them all so perhaps for `sg_api_usage`, we could take a less-conservative approach to match methods like in this PR. It actually gives a very …

[MAINT, MRG] A few small leftovers from API usage

---

sphinx_gallery/gen_gallery.py

@alexrockhill this short-circuits the processing when it's not requested. Should be safer and more efficient than doing some stuff then deciding to stop.

BUG: Short circuit when disabled

---

doc/configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_gen_gallery.py

This allows turning off of the API usage altogether, hopefully fixing the last issue with this new feature https://github.com/mne-tools/mne-python/pull/11132.
I looked into the other point, about suppressing the warnings but it looks like from the Sphinx-Gallery documentation that that has to be in the `conf.py` file, specific to that project so as far as I know it can't be done in an extension, unfortunately I think it just has to be done per-project.
cc @larsoner

[MAINT, MRG] Add unused option for API usage, set as default

---

sphinx_gallery/tests/test_full.py

@alexisthual should fix our error. Found it by looking for the actual link to `matplotlib.pyplot` and seeing that they changed the HTML filename

BUG: Update for matplotlib

---

sphinx_gallery/backreferences.py

The regex in `identify_names` also covered fully spelled out role names (`object` instead of `obj` etc.) which are however not recognized by sphinx.  
The [documentation](https://sphinx-gallery.github.io/stable/configuration.html#add-mini-galleries-for-api-documentation) lists only the correct short forms.
Closes #1008.

FIX: role names

---

README.rst
dev-requirements.txt
requirements.txt

- docs don't build with sphinx 5.2.1
- fix minimum required sphinx version in README.rst acc. to a6317fe7
Closes #1017. 
Not sure if https://github.com/sphinx-gallery/sphinx-gallery/blob/master/azure-pipelines.yml and https://github.com/sphinx-gallery/sphinx-gallery/blob/master/continuous_integration/azure/install.sh need to be updated too?

MNT: Fix required sphinx version

---

dev-requirements.txt

I'm terribly sorry, but I made a mistake in  #1019: it must read _"...don't build with sphinx 5.2.0"_. Sphinx 5.2.1 fixes the issue, so in requirements it must be of course `sphinx >= 3, != 5.2.0` instead of `!= 5.2.1`.

MNT: Fix erroneous commit c6ed4e

---

sphinx_gallery/gen_rst.py

In MNE-Python in our `resetter` we garbage collect and assert that no instances of some plotting classes remain anymore. Without this change, sometimes they would linger. With this change, they can be GC'ed correctly.
It's a bit of a mystery to me why this is the case, but it must create some bad circular reference that `gc` can't resolve somehow...

MAINT: Remove lingering ref

---

README.rst
doc/configuration.rst
doc/getting_started.rst
doc/index.rst
doc/maintainers.rst
doc/projects_list.rst
doc/syntax.rst

the current [link](https://nilearn.github.io/auto_examples/index.html) in https://sphinx-gallery.github.io/stable/projects_list.html results in 404.
- prevent the project lists in README.rst and projects_list.rst from
becoming out of sync by putting the projects list in a text file
to include in both rst files (there were already 2 projects more in
README.rst than in projects_list.rst)
- fix broken and some permanently redirected links reported by linkcheck
Github markup doesn't allow including files into README.rst, so we must
include from README.rst. Github doesn't process :ref: or :doc: roles
(they are shown literally) so we need to handle the Sphinx Gallery link
separately. The intersphinx links were replaced by ordinary links as
it's very unlikely that these targets would be changed …

DOC: fix 'Who uses Sphinx-Gallery' list

---

sphinx_gallery/gen_gallery.py

Produced with `'nested_sections': False`:
```
Handler <function generate_gallery_rst at 0x0000021152A7A440> for event 'builder-inited' threw an exception 
(exception: local variable 'subsection_index_toctree' referenced before assignment)
```
Unsure if this reflects intent, feel free to edit.

Fix "`subsection_index_toctree` referenced before assignment"

---

sphinx_gallery/directives.py
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_scrapers.py

e.g. `srcset="img.png 1.25x`. Browsers on my system default to zooming in by 125%, which is only undone by 1.25x. Changes:
1. `2.0x` -> `2.00x` everywhere
2. `2_0x` -> `2_00x` everywhere

Allow 2 decimal places in srcset

---

sphinx_gallery/gen_rst.py

Instead of using "here" as link text, tell the user what will happen if they click the link.
For example in the scikit-learn documentation the header looks like this:
There are two things that I think this PR improves:
1. Tell the user what will happen when they click the link. When I haven't looked at the example gallery for a while and come back as a "new user" (no memory of the past) I read the header and think "ok, so clicking will start a download, I don't want that. But then how do I get to the binder? It can't be downloading the binder. Weird. Well, let's start scrolling". Instead of realising what the link actually does, which is take you to the bottom of the page.
1. it uses the link text to tell the user something, compared to "click here". I think these days people know that …

Use descriptive link text for example page header

---

doc/advanced.rst

This section of the documentation has been updated to list explicit CSS examples.
One of these is for disabling the thumbnail text on hover.
Closes #1044.

Update advanced usage examples

---

doc/configuration.rst

#908 added a new paragraph (about `exclude_implicit_doc`) to the minigallery documentation, but it was placed in an odd position: the paragraph separates the paragraph introducing the `minigallery` directive from the paragraph describing an option for that directive, and is also somewhat removed from the other configuration discussion.  This PR swaps two paragraphs so that the section reads better.

Reorder paragraphs in the minigallery documentation

---

sphinx_gallery/gen_gallery.py

When the gallery directory path has an OS path separator in it, the separators need to be sanitized (on Windows) to be all forward slashes before the path is inserted into RST files.  This PR fixes a missing sanitization.
For comparison, here is another place in the codebase where the sanitization is performed:
https://github.com/sphinx-gallery/sphinx-gallery/blob/15ec1f945f21a8bf38645ffe6aab6e92f2f90170/sphinx_gallery/backreferences.py#L299-L300

Fixed a bug where backslashes in paths could show up in RST files

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

sphinx-gallery currently supports inline config options (e.g. `# sphinx_gallery_line_numbers = True`) as well as block ignore directives (i.e. `# sphinx_gallery_start_ignore` followed by `# sphinx_gallery_end_ignore`). By default, inline config options are left in place and included in the built documentation - but they can be removed by setting `"remove_config_comments": True`.
Currently, if `remove_config_comments = True`, inline config options are removed **before** block ignores are processed. This causes a bug. Suppose we have the following in our documentation:
```python
from tvm import testing
testing.utils.install_request_hook(depth=3)
```
If `remove_config_comments = False`, this will be correctly processed into:
```python
```
But if `remove_config_comments = True`, it instead …

BUG: Remove ignore blocks when remove_config_comments=True

---

doc/getting_started.rst
sphinx_gallery/directives.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_gallery.py

The idea of this PR is to develop a better solution to #921.
* Remove `dirhtml` blocking and associated test
* Add condition to `directives.visit_imgsg_html` to support `dirhtml` special case
I'm unaware of any other problem related to using the `dirhtml` builder.

Fix broken links when using dirhtml builder

---

doc/configuration.rst
sphinx_gallery/gen_gallery.py

Prevents warning about `plot_gallery` being a str but defaulting to bool when invoking with `-D plot_gallery=0 -b html $(ALLSPHINXOPTS)`.
Fixes gh-913

Adds `plot_gallery` as a string by default

---

sphinx_gallery/gen_gallery.py

`this_toctree` is not defined if the conditional is false, so don't add it to the index!  Follow up to #1071

FIX: indentation fix

---

doc/advanced.rst
doc/conf.py
mayavi_examples/README.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_scrapers.py

Closes #1075
1. Add a note in the documentation about how people can add their own mayavi scraper (copy-pasted version of our scraper, basically)
2. Add a warning in the Mayavi examples README about deprecation
3. Add a FutureWarning if they try to call `mayavi_scraper` themselves (rare probably, but why not)
4. Add a Sphinx warning on config resolution when `'mayavi'` is in the list of scrapers
5. Internally use `_MayaviScraper()` to avoid the deprecation warnings in our own builds
I think we should merge this and cut 0.12.0 (with a warning about the API change). Then the next PR after we change the version number to 0.13.dev0 can actually remove all Mayavi-related code.

API: Deprecate mayavi scraper

---

doc/configuration.rst

Adds a note to the Building without executing examples section on how to effectively configure a project that includes the html-noplot option in the Makefile.
Related to #913 and a minor doc followup to #1062. I ran into this as well w/ sphinx-gallery v0.11.1 and stumbled upon solutions in other projects e.g. scikit-learn/scikit-learn#22869, matplotlib/matplotlib#23870 so I figured it might be worth documenting here.

DOC: Add note for html-noplot to suppress config warning.

---

sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_full.py

In #1072, if the top level of a gallery had an index.rst instead of a README.txt, any subfolders _also_ had to have an index.rst instead of a README.rst.  The change here checks subdirectories as well for the presence of a README and allows subfolders to have a different README/index choice than the parent.

MNT: fix subfolder README detection

---

.github/workflows/release.yml
.github_changelog_generator
.gitignore
CHANGES.rst
MANIFEST.in
README.rst
doc/maintainers.rst
sphinx_gallery/__init__.py

1. Add custom `maintenance` and `documentation` label support for github-changelog-generator and use them
2. Simplify github-changelog-generator use by a `.github_changelog_generator` file
3. Remove `Closed Issues` headings in changelog (we should really just track changes-by-PR)
4. Update release docs
5. Bump version number
6. Add automated PyPI release when we cut a GitHub release (shortens release process)
Will look at the rendered docs and merge if it looks good, cut a release, and then check to make sure things propagated to PyPI!

MAINT: Release 0.12.0

---

sphinx_gallery/__init__.py

Release appears to have worked, let's move to 0.13.dev0
https://pypi.org/project/sphinx-gallery/#history

MAINT: Bump version to dev

---

sphinx_gallery/gen_gallery.py

Without this, it can come up against a next text block, e.g. subsection title, which will cause indentation error.
Example below of issue raising `...\auto_tutorials\index.rst:204:Explicit markup ends without a blank line; unexpected unindent.`
Before:
```rst
.. toctree::
:hidden:
/auto_tutorials/01_KalmanFilterTutorial
/auto_tutorials/02_ExtendedKalmanFilterTutorial
/auto_tutorials/03_UnscentedKalmanFilterTutorial
/auto_tutorials/04_ParticleFilter
/auto_tutorials/05_DataAssociation-Clutter
/auto_tutorials/06_DataAssociation-MultiTargetTutorial
/auto_tutorials/07_PDATutorial
/auto_tutorials/08_JPDATutorial
/auto_tutorials/09_Initiators_&_Deleters
/auto_tutorials/10_Simulation_&_Tracking_Components
Filters
-------
Here are some tutorials which cover additional filtering techniques.
``` …

FIX: Add blank line at end of table of contents block

---

sphinx_gallery/gen_rst.py

This resolves an issue with HTML being ANSI sanitized, which can cause issues.
For example, this breaks Plotly when rendering with plotly.min.js embedded, due to ANSI escape in JS code, causing plots to not be displayed.
Relates to original #838

FIX: Only ANSI sanitize non-HTML output

---

doc/configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_notebook.py

Fixes #1091.
> Now that we have jupyterlite included, we should remove the default "%matplotlib inline", as it breaks under jupyterlite and it is no longer necessary under jupyter.
My approach with the test was simply to remove the assertion, but I am sure there might be a better way to do it. Any feedback is welcomed.

Remove default '%matplotlib inline' line

---

README.rst
doc/projects_list.rst

- remove semicolon left after rewrite in 3825d9f
- uniformly apply capitalization to project names in list
- remove double entry of "Sphinx Gallery" in `project_list.rst` created by 3825d9f

Fix project list

---

sphinx_gallery/scrapers.py

The matplotlib backend is set to `agg` in the function `_import_matplotlib()`, which is called both (1) when resetting matplotlib for each example and (2) when scraping each code block for matplotlib plots (`matplotlib_scraper()`).  The forcing of the backend to `agg` in the latter case means that an example is unable to make use of non-`agg` backends.
My particular use case is that I want to use `mplcairo` in an example to show how to use its blending operators, e.g., the example begins:
```python
import matplotlib
matplotlib.use("module://mplcairo.base")
...
```
With the current code, the matplotlib backend is immediately set back to `agg` after scraping the first code block, and so the subsequent code blocks (and the eventual plot) do not work properly.
This PR replaces the call of …

Avoid potentially changing the matplotlib backend when scraping

---

sphinx_gallery/interactive_example.py
sphinx_gallery/tests/test_interactive_example.py

I realised this when trying to use the feature on scikit-learn where there are nested folders 
You can also see it in sphinx-gallery, go to https://sphinx-gallery.github.io/stable/auto_examples/no_output/just_code.html, click on JupyterLite button, you will get a HTTP 404.
~Let me know if you want me to add a test for this!~ This was easy to modify an existing test so I did it!

Fix JupyterLite URL with nested gallery folders

---

doc/configuration.rst

This is a new thing in jupyterlite 0.1.0b19, see https://github.com/jupyterlite/jupyterlite/blob/main/CHANGELOG.md#010b19 for more details.

DOC Update JupyterLite doc after JupyterLite 0.1.0b19 release

---

.circleci/config.yml
azure-pipelines.yml
continuous_integration/azure/install.sh
doc/configuration.rst

Fix #1103.
Also used this PR to tweak the doc, it makes more sense to mention jupyterlite-sphinx version.

CI Install jupyterlite-pyodide-kernel in CI

---

sphinx_gallery/gen_rst.py

Add one more sanitizing case (needed for https://matplotlib.org/stable/gallery/text_labels_and_annotations/dfrac_demo.html#sphx-glr-gallery-text-labels-and-annotations-dfrac-demo-py)
Closes #1002.

Fix thumbnail text formatting

---

dev-requirements.txt
requirements.txt

Minimum version was changed to >=4 in README.rst in caef783.

MNT: Sync minimum sphinx version with README.rst

---

README.rst

This PR aims to add [`PyGMT`](https://www.pygmt.org/latest/) (A Python interface for the [Generic Mapping Tools](https://www.generic-mapping-tools.org/)) to the list "Who uses Sphinx-Gallery". The Gallery can be found at https://www.pygmt.org/latest/gallery/index.html.

Add PyGMT to list "Who uses Sphinx-Gallery"

---

sphinx_gallery/interactive_example.py
sphinx_gallery/tests/test_interactive_example.py

Turns out #1105 was not the right fix, we need to use a relative URL. For example if I copy `_build/html` to a repo like https://github.com/lesteve/sphinx-gallery-jupyterlite, an example html page is 
https://lesteve.github.io/sphinx-gallery-jupyterlite/auto_examples/no_output/plot_raise.html
and I want the link to go to
`https://lesteve.github.io/sphinx-gallery-jupyterlite/lite` so `../../lite`. `/lite` as done in #1105 goes to `https://lesteve.github.io/lite` which is incorrect. If the example is one folder above you want `../lite` instead. This is why I use `os.path.relpath` to get the root URL.
I have added more tests as well with a nested gallery folder (aka sub-gallery I think).

FIX JupyterLite button links

---

doc/conf.py
doc/configuration.rst
sphinx_gallery/interactive_example.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_interactive_example.py
sphinx_gallery/tests/tinybuild/doc/conf.py

To be able to run in JupyterLite, notebooks may need additional code, e.g. `%pip install seaborn` since `seaborn` (or any pure-Python code) is not part of Pyodide.
Also this allows to put a warning in a markdown cell to manage user expectations at the beginning of the notebook. We could add a better warning for notebooks that we don't expect to run any time soon, e.g. the ones using pyvista.
No tests or doc for now, but this still may be enough to get some feed-back on the code.
xref https://github.com/sphinx-gallery/sphinx-gallery/issues/1100

ENH Add functionality to modify Jupyterlite notebooks based on their content

---

sphinx_gallery/interactive_example.py
sphinx_gallery/tests/test_interactive_example.py

This raises an informative error when `sphinx_gallery_conf['jupyterlite']` contains keys that are not expected.
This is useful to detect typos in the key.

ENH raise error in check_jupyterlite_conf with unknown key

---

doc/advanced.rst
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/doc/conf.py
sphinx_gallery/tests/tinybuild/examples/plot_webp.py

and update docs on supported formats.
[WebP](https://en.wikipedia.org/wiki/WebP) yields much smaller file sizes than optimized png in only very little more time. For the Matplotlib docs with 2637 `sphx-glr...` files I got the following results:
|                                          | Total size in MB | Percentage of orginal size | Extra time|
|---------------------------- |:-----------------:|:---------------------------:|------------|
plain png                           | 162.4 | 100 % | -  |
optipng -o7                       | 115.9 | 71 %  | 4:35 hrs |
webp lossless quality=100 | 65.5  | 40 % | 9 mins  |
<br>  
<hr>  
My first thought was to integrate the `_KNOWN_IMG_EXTS` list into the docstring of [`matplotlib_scraper`](https://github.com/sphinx-gallery/sphinx-gallery/blob/b17bf5 …

ENH: Add support for WebP

---

sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_scrapers.py

Follow-up of #1120. I tried to clean-up the namings and add a few docstrings.

CLN Clean up naming of early config validation

---

doc/configuration.rst
examples/plot_6_function_identifier.py
sphinx_gallery/backreferences.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py

When adding mini-galleries for API documentation, only the 5 roles `func`, `math`, `attr`, `obj` and `class` were taken into consideration. It is, however, common practice to define a default role (e.g. `:py:obj:`) using the `default_role` entry in `conf.py`. This PR enables the creation of backreferences for references without an explicit role if the default role in `conf.py` is one of the five roles listed above. Note that only the default role definition in `conf.py` is taken into consideration, i.e. setting the default role using the [`.. default-role::`](https://docutils.sourceforge.io/docs/ref/rst/directives.html#default-role) directive is not taken into account.
Further, separate titles (`Title <link>`) and suppressed link creations (`!no.link`) are handled correctly now.
The …

ENH: Create backreferences for default roles

---

doc/advanced.rst

`visibility:hidden; height: 0px` still keeps margins, creating a large  amount of whitespace. `display: none` is the correct way to remove an HTML element completely.

Correctly hide download buttons

---

README.rst

There is a generic Zenodo reference that always points at the latest version. This is now used.
(Btw, it looks like there isn't a Zenodo version for 0.13.0.)

MAINT: Fix Zenodo reference

---

.circleci/config.yml
azure-pipelines.yml
setup.cfg
sphinx_gallery/tests/test_load_style.py

In Sphinx 7.0.1 support for build_sphinx was removed. I think this is the way to go.
Also installs `imageio` as I think that is not an expected failure...
Edit: ~install `absl-py` for Sphinx-dev test~. Also, sphinx-dev adds `?hash(?)` to href-link so removed the closing " from the test.

MAINT: Replace build_sphinx with sphinx-build

---

doc/advanced.rst

Related to #1144 (was not really required to do the edit in the issue, could just have added this, but didn't think like that at the time).
The original issue is still there though.

DOC: Add link to sphinxcontrib-svg2pdfconverter

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

Closes #1150.
Following up on the discussion in issue sphinx-gallery/sphinx-gallery#1150, I'd like to propose this PR to improve the compatibility between _LoggingTee and TextIO. It also includes some tests to keep the coverage complete.
Judging from the previous comments, the non-compatibility was already an issue for other packages (e.g. seaborn). In this PR, the classic attributes of [TextIOBase](https://docs.python.org/3/library/io.html#io.TextIOBase) and of [IOBase](https://docs.python.org/3/library/io.html#io.IOBase) (inherited) are all implemented.
This should prevent further issues on the compatibility between the expected stdout and _LoggingTee. I am, of course, open to reverting to adding only the "encoding" attribute if you find it safer/more appropriate. However, this should …

Make _LoggingTee compatible with TextIO

---

sphinx_gallery/gen_rst.py

Changes output from:
```
Total running time of the script: ( 0 minutes 0.197 seconds)
```
To:
```
Total running time of the script: (0 minutes 0.197 seconds)
```

Remove extra spaces in reported running time

---

sphinx_gallery/docs_resolv.py
sphinx_gallery/tests/test_full.py

CI is failing with sphinx dev with error:
(see: https://dev.azure.com/sphinx-gallery/sphinx-gallery/_build/results?buildId=1368&view=logs&j=18f51a03-7fab-57d7-f724-30d2d83bc222&t=7c53da0f-8616-5987-83c8-9378d265c3e8&l=1124)
```
ERROR at setup of test_timings ________________________
/usr/share/miniconda/lib/python3.10/site-packages/sphinx/events.py:96: in emit
results.append(listener.handler(self.app, *args))
sphinx_gallery/docs_resolv.py:471: in embed_code_links
_embed_code_links(app, gallery_conf, gallery_dir)
sphinx_gallery/docs_resolv.py:324: in _embed_code_links
doc_resolvers[this_module] = SphinxDocLinkResolver(
sphinx_gallery/docs_resolv.py:146: in __init__
if doc_url.startswith(('http://',/ 'https://'))/:
E   AttributeError: 'PosixPath' object has no attribute 'startswith'
The …
```

Maint: Fix `app.builder.outdir` as Sphinx now using pathlib

---

.gitignore
continuous_integration/azure/install.sh

CIs are taking 40+ minutes in https://github.com/sphinx-gallery/sphinx-gallery/pull/1154 which is too long. Let's see if `mamba` goes faster. If not, we should just stop using `conda` since we can just use `pip` instead.
It might be worth moving to GitHub Actions as well at some point...

MAINT: Speed up conda solving

---

doc/configuration.rst
sphinx_gallery/docs_resolv.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_full.py

Fixes some nitpicks in backreferences docs.
Edit:
This PR now does the following:
* Minor wording updates in backreferences/linking docs
* Update docstring `SphinxDocLinkResolver.resolve`
* Change `prefer_full_module` to set instead of list, like other similar configs (e.g., exclude_implicit_doc)
* Use the full module (instead of short module) name when matching `prefer_full_module` - gives you finer control and brings it in line with what `exclude_implicit_doc` does.
* Update and add a test to better test `_get_short_module_name`

MAINT Update backreferences docs and add tests

---

sphinx_gallery/utils.py

This resolves an issue where the system default encoding for opening a file is not UTF-8, whereas the encoding default for string encode method is UTF-8, and such hash differs depending on OS.
Related to #722 which originally attempted to resolve inconsistencies across OSs.

Ensure consistent encoding for md5sum generation

---

continuous_integration/azure/install.sh
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/doc/conf.py
sphinx_gallery/utils.py

Improve `tinybuild` by
1. Adding something that prints what's detected as modified when rerunning
2. Only replacing thumbnails when they change (which reduced the number of modified files in the test)
3. Slightly better reporting on failure
It's entirely possible this will fail for older versions of Sphnix... let's see!

MAINT: Make outdated check better

---

doc/configuration.rst
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_full.py

Hi folks, https://github.com/matplotlib/matplotlib/pull/26472 changed the wording of the gui error message, so this PR updates the filters and docs to the new warning message wording.  This is gonna be in the 3.8 release. 
I wonder if there's a better way to do this though.

updated mpl gui warning catcher to new error message

---

sphinx_gallery/docs_resolv.py
sphinx_gallery/gen_gallery.py

MAINT: Fix for Sphinx 7.2

---

sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_backreferences.py

Ensure we get to the `else` in `visit_Attribute`:
https://github.com/sphinx-gallery/sphinx-gallery/blob/451ccba1007cc523f39cbcc960ebc21ca39f7b75/sphinx_gallery/backreferences.py#L89
This is probably tested in `test_full.py` but nice to have in a more 'unit' test.

MAINT Add to `test_identify_names` so class property tested

---

sphinx_gallery/backreferences.py
sphinx_gallery/gen_rst.py
sphinx_gallery/py_source_parser.py

Also expands `ast.Module` typing as we use 'ast node' everywhere else.

MAINT Lint - fix ast node type in docstrings

---

sphinx_gallery/py_source_parser.py
sphinx_gallery/tests/test_py_source_parser.py

The checks for mismatched "ignore" blocks were not detecting either "start" or "end" flags, and just comparing `0 == 0`. This PR:
- fixes these regex evaluations
- corrects the name of "start" flag in the `remove_ignore_blocks` docstring
- updates the test to simulate more realistic use case with a multi-line code block

MAINT Fix check for mismatched "ignore" blocks

---

sphinx_gallery/backreferences.py

This fixes #1158 (or, is intended to help at least) based on the proposed solution in that issue and discussion elsewhere.
Hopefully this solution makes sense but I'm happy to rework as I came up with a lot of ways to do effectively the same thing. I am not too intimately familiar with the import system (at least I was not when I started on this) and definitely a little lost in some of this sphinx-gallery code.
Either way I know @lucyleeow had also suggested this should possibly be a config and I am happy to add that if you want it. I will also read though to see if there's a good spot to put some of this info in the docs.
It's also worth noting that now setuptools 68.1.0 has been released, which should fix the specific problem (case-insensitive imports from editable installs) that …

Avoid importing new modules in backrefs

---

.circleci/config.yml
.github/workflows/circle_artifacts.yml
.gitignore
MANIFEST.in
continuous_integration/azure/install.sh
doc/Makefile
doc/getting_started.rst
setup.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/tinybuild/doc/Makefile

For a while I've wanted a full listing of example computation times. This PR writes them to the `src_dir` root as `sg_execution_times.html`, which I think is hopefully safe enough.
Snuck in some cleanups of `pytest.mark.parametrize` so our test names can be a bit shorter in the terminal, too.

ENH: Write all computation times

---

CHANGES.rst

I think support was dropped in #1197

DOC Note support for python 3.7 dropped in release notes

---

sphinx_gallery/gen_gallery.py

After working on https://github.com/mne-tools/mne-python/pull/12013#issuecomment-1736018069 I wanted to port over some changes that I think will be generally helpful. After some simplifications and tweaks to the diagram to make it more readable, esp. with a dense layout with overlaps, this is what I see:
| | before | after |
| -- | -- | -- |
| SG | ![image](https://github.com/sphinx-gallery/sphinx-gallery/assets/2365790/66d0216f-bc47-4fe5-8daf-9db2662daf09) | ![image](https://github.com/sphinx-gallery/sphinx-gallery/assets/2365790/54113b0d-9192-4079-a9a3-822b4de8f5c3) |
| MNE | ![image](https://github.com/sphinx-gallery/sphinx-gallery/assets/2365790/08c32208-08af-4cfb-85ae-ec3df4bdbe88) | ![image](https://github.com/sphinx-gallery/sphinx-gallery/assets/2365790/7c77bb3c-2663-4296-9cf3-e6301 …

ENH: Improve API usage graph

---

.circleci/config.yml
.circleci/setup_bash.sh
.gitignore

CircleCI is sometimes a bottleneck, this attempts to refactor it to use a single `setup_env` step whose workspace then gets reused by the `html`, `tinybuild`, and `latexpdf` jobs.

MAINT: Improve CircleCI time

---

doc/contribute.rst
doc/index.rst

Per https://github.com/sphinx-gallery/sphinx-gallery/issues/1222#issuecomment-1793925224, started a contributing guide so there'd be a place to document stuff like testing. Feel free to adopt to your culture and community goals. 
I mostly stuck to the readme but made everything a `pip` command 'cause terrible things seem to happen when stuff is mixed & I figure more experienced contributors will just use whatever they're used to. 
Figured you all didn't want to maintain copy of the github workflow, so linked out to github's contributing guide for anything that wasn't specific to your workflow.

DOC: contributing guide

---

doc/configuration.rst

Our config doc is getting long and unwieldy. Hopefully this can help people find things.
Also combined (``show_api_usage`` and ``api_usage_ignore``) and (``reset_modules`` and ``reset_modules_order``) under one heading.

DOC Put configuration list under headings

---

.circleci/docs_deploy.sh

Closes #1235
Looking at https://github.com/sphinx-gallery/sphinx-gallery.github.io/commits/master you can see I broke stuff in https://github.com/sphinx-gallery/sphinx-gallery/pull/1216. I did the equivalent of the two steps in this PR -- namely, deleting two folders that were persisted to the workspace that should not have been -- and pushed to https://github.com/sphinx-gallery/sphinx-gallery.github.io and now docs are deployed properly. So this PR makes it so that hopefully the next `dev` and `stable` deployments work properly!

MAINT: Fix deployment

---

doc/contribute.rst

Fix hyperlink formatting and unify "tinybuild" formatting as inline literal.

DOC: Fix formatting in contribute.rst

---

sphinx_gallery/py_source_parser.py

This fixes the following warnings:
```
.../sphinx_gallery/py_source_parser.py:101: DeprecationWarning: ast.Str is
deprecated and will be removed in Python 3.14; use ast.Constant
instead
and isinstance(node.body[0].value, ast.Str)
.../sphinx_gallery/py_source_parser.py:113: DeprecationWarning:
Attribute s is deprecated and will be removed in Python 3.14; use
value instead
if len(node.body[0].value.s) and node.body[0].value.s[0] == "\n":
```
`ast.Str` was deprecated in 3.8 (and returned an `ast.Constant` anyway), which is the minimum requirement here. I can't find `s` or `value`, so I'm not sure when they were deprecated exactly.

Fix AST deprecation warnings

---

sphinx_gallery/recommender.py

See also scikit-learn/scikit-learn#27969. Without specifying the encoding such as utf-8, some systems would use other codecs (e.g. gbk) which cannot decode some characters (e.g. `–`, `“`, `”`). This PR specifies `encoding="utf-8"`.

BUG: `UnicodeDecodeError` in recommender

---

sphinx_gallery/gen_gallery.py
sphinx_gallery/scrapers.py
sphinx_gallery/tests/test_scrapers.py

Three things:
- Validate `image_srcset` once during configuration, instead of repeatedly on every scraper run. Note, I also passed the scaling numbers through a set, in order to prevent saving extra times.
- Simplify the animation part of the scraper; instead of looping through all animations to match a figure, use a dictionary for direct lookup.
- Add a note about `kwargs` to `matplotlib_scraper`. I was confused why nothing seemed to call it with `kwargs`, but was able to find it in other parts of the documentation. So I mentioned that in the docstring as well.

Simplify Matplotlib scraper

---

README.rst

Add the packages HyperSpy (hyperspectral data analysys), pyxem (4DSTEM data analysis) and kikuchipy (EBSD data analysis) to `Who uses Sphinx-Gallery`.
With the 2.0 release, [HyperSpy](https://hyperspy.org/hyperspy-doc/current/auto_examples/index.html) has adopted a sphinx gallery as part of the documentation. The documentation of [kikuchipy](https://kikuchipy.org/en/stable/examples/index.html)  and [pyxem](https://pyxem.readthedocs.io/en/stable/examples/index.html) also include a gallery of examples.

Add HyperSpy and kikuchipy to 'who uses'

---

.github/workflows/tests.yml
continuous_integration/install.sh
dev-requirements.txt
doc/conf.py
doc/configuration.rst
doc/utils.rst
sphinx_gallery/backreferences.py
sphinx_gallery/directives.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/sorting.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_sorting.py
sphinx_gallery/tests/tinybuild/doc/conf.py
sphinx_gallery/tests/tinybuild/doc/make.bat
sphinx_gallery/tests/tinybuild/doc/minigallery.rst

[ENH] Minigallery can take arbitrary files/glob patterns as input

---

doc/configuration.rst
doc/utils.rst
sphinx_gallery/directives.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/doc/conf.py

Follow on from #1226, this pr:
* has the sortkey work on full path to account for subdirectories
* fixes the sortkey test and adds check that test is working
* updates docs

ENH: minigallery_sort_order on full path

---

sphinx_gallery/gen_rst.py

Add the missing full stop in the examples downlaod note.
Closes #1254

fix: Missing full stop in download message

---

doc/conf.py

closes #1262
It seems PST does not have the TOC problems described in https://github.com/sphinx-gallery/sphinx-gallery/pull/944#discussion_r916603188 and gives us the sub gallery sub heading in the LHS TOC.
I'll double check the rendered docs to make sure it looks okay.

DOC Use 'nested_sections' `True` for docs

---

.pre-commit-config.yaml
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/interactive_example.py
sphinx_gallery/py_source_parser.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py

As Ruff [claims](https://pypi.org/project/ruff/0.0.47/#:~:text=ruff%20is%20compatible%20with%20Black,that%20are%20obviated%20by%20autoformatting.) full compatibility with Black, it makes sense just to use one tool for both to prevent eventual collisions

lint: switch from Black to Ruff's "Black"

---

pyproject.toml

Cut part of would #1267 as simplification of `pytest` config improving reliability in IDE
also adding `--color=yes` to make the test logs easier to navigate :rabbit: 
cc: @lucyleeow

pyproject: cleaning pytest config

---

.github/workflows/label-check.yml

Follows on from #1270, I agree this CI test is confusing and its annoying to have it be the cause of a PR being 'red'.
This is just a temporary, slight improvement, to at least help prevent confusion for new contributors: change the CI workflow name so contributors can easily see why this test has failed. Happy to change change wording. It's similar to what scikit-learn has for their 'Check Changelog'  check.
Also skips drafts and improves message, copied from #1270.

More informative title for 'check label' CI workflow

---

doc/configuration.rst

- The example of how to use `reset_argv` is wrong, or at least misleading on two counts. One, it must return an iterable in all cases, so there should be a default case returning `[]`. Two, the value of `script_vars['src_file']` is an absolute path, not just a filename, so just `sample1.py` won't ever be matched.
- Rewrite the sample regex for `ignore_repr_types` so it actually does what's described in the text.

BUG: Fix errors in example usage of ignore_repr_types and reset_argv

---

sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_scrapers.py

`image_srcset` config added in #808. Originally in that PR an empty string was meant to mean save the usual image: https://github.com/sphinx-gallery/sphinx-gallery/pull/808#issue-855178549. Later on we changed it to never neededing the empty string: https://github.com/sphinx-gallery/sphinx-gallery/pull/808#issuecomment-823736082
This removes the redundant config checking as `image_srcset` should not be taking an empty string.
First noticed: https://github.com/sphinx-gallery/sphinx-gallery/pull/1241/files#r1542174678

Remove leftover config checking of `image_srcset`

---

sphinx_gallery/tests/test_gen_rst.py

See: https://github.com/sphinx-gallery/sphinx-gallery/pull/1151/files#r1269969694
Remove unused fixture

Fix typo in `test_fileno`

---

README.rst

It took me a while to find the link to docs, and mostly, it is mentioned in the readme, or there is a docs badge, but there is none of these yet...
Also, it may be a good idea to add a section with a simple/quick explanation of how to use it...
cc: @lucyleeow

readme: add link to docs

---

doc/configuration.rst

I think we prefer FFMpeg now and the buggy was probably for matplotlib < 3.3.1

DOC Update FFMpeg note in conf animation docs

---

.circleci/config.yml
.github/install.sh
.pre-commit-config.yaml
CHANGES.rst
dev-requirements.txt
doc/advanced.rst
doc/conf.py
doc/configuration.rst
doc/sphinxext/sg_doc_build.py
sphinx_gallery/backreferences.py
sphinx_gallery/directives.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/interactive_example.py
sphinx_gallery/scrapers.py
sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/test_notebook.py
sphinx_gallery/tests/test_scrapers.py
sphinx_gallery/tests/tinybuild/doc/conf.py
sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py
sphinx_gallery/tests/tinybuild/utils.py

Closes #1286
1. Support fully qualified names of classes / callables
2. Add aliases for our own ones like `"FileNameSortKey"` as an alias for `"sphinx_gallery.sorting.FileNameSortKey"`
3. Keep `sphinx_gallery_conf` clean: don't store `app` in there or any functions
1. Check for existence when filling the conf
2. Load them on the fly when they need to be used
4. Add to release notes
Kind of a pain to figure out but ultimately it does seem cleaner!

BUG: Fix serialization with Sphinx 7.3

---

doc/configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/sorting.py
sphinx_gallery/tests/test_sorting.py

Closes  #1293. Should wait for #1289.
Note: For simplicity, I've modified `ExplicitOrder` to include the wildcard. This is backward-compatible. One could alternatively make an independent internal `ListOrder` sortkey if `ExplicitOrder` should not be touched.
Note 2: Elements in the ordered_list that does not exists as a subsection are silently ignored. This is present behavior and we cannot detect this as long as the pattern `sorted(..., key=)` with a key function. If we want to warn on that as well (I've proposed that in in #1293), we would need to write a custom code path for sorting if 'subsection_order' is a list. For simplicity, I've not done that. It's always possible to do this later.

ENH: Allow plain list as subsection_order and support a wildcard

---

doc/conf.py
sphinx_gallery/docs_resolv.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_docs_resolv.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_gen_rst.py

Fixes an incorrect traceback:
```
../examples/inverse/read_inverse.py failed leaving traceback:
Traceback (most recent call last):
File "/home/circleci/project/examples/inverse/read_inverse.py", line 26
meg_path = data_path / "MEG" / "sample"
^
```
to:
```
../examples/inverse/read_inverse.py unexpectedly failed to execute correctly:
Traceback (most recent call last):
File "/home/larsoner/python/sphinx-gallery/sphinx_gallery/gen_rst.py", line 961, in execute_code_block
code_ast = compile(
^^^^^^^^
File "/home/larsoner/python/mne-python/examples/inverse/read_inverse.py", line 43
print(f"Number of vertices on the right hemisphere: {len(src[1]["rr"])}")
^^
SyntaxError: f-string: unmatched '['
```
By just prepending `"\n"`'s when trying to `compile` the code.
Also cleans up some code since …

BUG: Fix bug with traceback with SyntaxError

---

dev-requirements.txt
doc/contribute.rst

Also updates our dev Install Dependencies doc - we no longer have a `requirements.txt` file and graphviz is already in dev requirements.

MAINT Add `sphinxcontrib-video` to dev requirements

---

doc/advanced.rst
sphinx_gallery/backreferences.py
sphinx_gallery/block_parser.py
sphinx_gallery/directives.py
sphinx_gallery/gen_rst.py
sphinx_gallery/py_source_parser.py
sphinx_gallery/recommender.py
sphinx_gallery/scrapers.py
sphinx_gallery/sorting.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py

It's better to give the "Block" concept its own entity and thus be able to access it's attributes by name.
I anticipate that I will need to expand the Block data to support per-block options for #1283, and that expansion will be simpler when blocks are no longer pure tuples. I've decided to split this out for simpler review and advertise this PR as code cleanup.

MNT: Turn the block tuple into a namedtuple

---

doc/contribute.rst

These appear to have been accidental.
I just re-wrapped these paragraphs so that no lines started with a space (hopefully wrapped at the right width for you.)

DOC: Remove definition lists from contribution guide

---

sphinx_gallery/docs_resolv.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py

Some registries may contain multiple modules (e.g., Python contains all the standard library modules, or Matplotlib contains modules in the `mpl_toolkits` namespace), and the previous lookup by the intersphinx mapping _only_ could cause these to be missed. There was already some special casing for Python, but this is now extended to all inventories, fixing the case for Matplotlib as well.
Fixes matplotlib/matplotlib#28250

Fix handling of multi-module intersphinx registries

---

sphinx_gallery/backreferences.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/interactive_example.py

Picked the most common one (it's also shorter) to use everywhere for consistency.

MNT Use `os.sep` everywhere

---

sphinx_gallery/interactive_example.py
sphinx_gallery/tests/test_interactive_example.py

A while ago, there was some CircleCI limitation that prevented JupyterLite to work inside CircleCI artifact, see https://github.com/sphinx-gallery/sphinx-gallery/pull/977#issuecomment-1330438821 if you are really curious.
It seems something has changed now, but for some reason you need to be explicit and add `index.html` to the URL, don't ask me why ... edit: I found this very old [discussion]( https://discuss.circleci.com/t/circle-artifacts-com-not-using-index-html/320) from 2015 but nothing more recent.
Let's try this in this PR!
An example of a recent scikit-learn doc build CircleCI artifact [example](https://output.circle-artifacts.com/output/job/13caab71-1b1d-444a-b316-93ac215ec6ef/artifacts/0/doc/auto_examples/release_highlights/plot_release_highlights_1_5_0.html)
The JupyterLite …

FIX Jupyterlite in CircleCI artifact

---

sphinx_gallery/_static/sg_gallery.css
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_rst.py

Closes: #1066 (related to #1085).
Note that given the padding was `10px 10px 10px 10px`, the bottom exposes the top content of the next truncated line:
I've adjusted the clamp to 6 lines, so longer texts use full space, and smaller ones are automatically reduced (states forced to :hover):

Introduction tooltip corresponds to the first paragraph

---

sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_full.py

Fixes https://github.com/sphinx-gallery/sphinx-gallery/pull/1332#issuecomment-2244559782
When top level index.rst is passed by user we were not generating the zipfiles.

FIX generate zipfiles when index passed by user

---

doc/configuration.rst
sphinx_gallery/directives.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/testconfs/src/plot_1.py

Closes #1354
Amend the minigallery directive, such that when `backreferences_dir` is `None`, we simply treat all entries as str paths and glob them.
I thought about adding additional check to the minigallery entries, to make sure they are not objects. But it would be very unusual to have a file named e.g., `sphinx_gallery.sorting.ExplicitOrder` in the source dir?
Happy to add a check though, WDYT @larsoner ?
Also fixes a bug where we were not converting `examples_dirs` and `gallery_dirs` to list when given as str.
Note to self: look into: https://github.com/sphinx-gallery/sphinx-gallery/pull/1226#discussion_r1690889760

FIX Allow str path minigallery entries when backreferences off

---

sphinx_gallery/docs_resolv.py

In the case of class attributes, only the short module name was attempted as fallback, instead of complying with the `prefer_full_module` setting.

Fix linking to class attributes with prefer_full_module

---

pyproject.toml
sphinx_gallery/directives.py
sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_gen_gallery.py

closes #1356
Uses `relative_to` to get target gallery path - in particular improves the part where we figure out if the file is in a subgallery/subfolder. I think the `relative_to` is more robust and I think it should work as intended.
e.g., 
one glob match: `'.../sphinx-gallery/sphinx_gallery/tests/tinybuild/examples_rst_index/examp_subdir2/plot_sub2.py'`
example dir path: `.../sphinx_gallery/sphinx_gallery/tests/tinybuild/examples_rst_index/`
Uses `resolve` to get abs paths.
cc @story645

Improve minigallery directive path input resolution

---

sphinx_gallery/_dummy/__init__.py
sphinx_gallery/_dummy/nested.py
sphinx_gallery/backreferences.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_backreferences.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/tinybuild/doc/conf.py
sphinx_gallery/tests/tinybuild/doc/index.rst
sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py

This fixes several cases of missing backreferences in Matplotlib's `mpl_toolkits` namespace, which need the full module name for referencing into Sphinx.
For example, [`Axes3D.plot`](https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.plot.html) only has one back reference:
but with this change we have all these:

Obey prefer_full_module setting when finding backreferences

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_backreferences.py

When using the sphinx config `default_role = 'obj'`, one can leave out the prefixes :meth: and similar and directly reference code objects using backticks. In there, one can use the sphinx prefix modifiers `.` and `~`.
Examples from Matplotlib where these show up:
This PR enhances `_sanitize_rst` to remove the prefix modifiers:
- `.MyClass` --> MyClass
- `~.MyClass.close` --> close

ENH: Improve _sanitize_rst

---

sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py

I couldn't figure out why my MNE doc build was always rebuilding. It's because the `re.compile(<str>.join(<set>))` will not have a stable `repr` run-to-run because `set` does not have a stable order run-to-run. This PR fixes it. Not easy to add a test because it would require invoking `sphinx` twice, and even then would be a Heisenbug to detect. Hopefully https://github.com/sphinx-doc/sphinx/pull/12741 can move forward to make this more easy to detect.

FIX: Fix stability of stored compiled regex

---

doc/configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/conftest.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_gen_rst.py

closes #1382
Bug introduced by refactor in https://github.com/sphinx-gallery/sphinx-gallery/pull/1332
When the first gallery in the example gallery loop, in `generate_gallery_rst`, is one with its own `index.rst` file, the `indexst` variable does not exist which is a problem because we pass it to `_finish_index_rst`. This variable is not used in `_finish_index_rst` when the gallery has its own index.rst file but `_finish_index_rst` does various other things so needs to be run always, even when the gallery has its own `index.rst`.
Adds test.
Will do a patch release once this is merged

Fix `indexst` variable does not exist when own index gallery is first

---

doc/configuration.rst
sphinx_gallery/gen_gallery.py

Allow to disable writing computation times to allow for reproducible builds.
Default to not write durations. if SOURCE_DATE_EPOCH indicates that a reproducible build is wanted.
Helps with https://github.com/pygraphviz/pygraphviz/issues/541

Allow to disable writing computation times

---

sphinx_gallery/scrapers.py

Changes to using os.path.relpath cause on windows `Path.relative_to` yields the following build errors: 
```python-traceback
File "C:\Users\story\miniconda3\envs\mpl-dev\Lib\site-packages\sphinx_gallery\scrapers.py", line 276, in _anim_rst
video_uri = video.relative_to(gallery_conf["src_dir"]).as_posix()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\story\miniconda3\envs\mpl-dev\Lib\pathlib.py", line 682, in relative_to
raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'C:\\Users\\story\\Projects\\matplotlib\\doc\\gallery\\animation\\images\\sphx_glr_simple_scatter_009.mp4' is not in the subpath of 'C:/Users/story/Projects/matplotlib/doc'
```

BUG: make _anim_rst windows compatible

---

doc/configuration.rst
sphinx_gallery/directives.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_gen_gallery.py

Follows after #1391
* Moves the section on custom sort keys, so it does not live with the subsection docs as it applies more generally to subsection order configs as well as minigallery sort
* Adds info on exactly what is being sorted for all 3 configs that allow custom sorting
* Adds note that `within_subsection_order` allows class input, which will be instantiated by SG
* Minor update to the 'Managing multiple gallaries' section
* Adds docstring and comments to `_get_callables`
@drammock if you have time, would you take a look at this as it follows on from your PR, thank you

DOC Improve custom sort key docs

---

.circleci/config.yml
.github/install.sh
doc/configuration.rst
pyproject.toml
sphinx_gallery/interactive_example.py
sphinx_gallery/tests/test_interactive_example.py

I noticed that while JupyterLite dropped the "retro" string in the URL for the Notebook interface at some point in time, `sphinx-gallery` still seems to have it – and I recently hit this on https://github.com/scikit-image/scikit-image/pull/7644 where I wanted to use it for the gallery notebooks. This PR fixes it, so that the buttons inserted by `sphinx-gallery` now open the correct link:
`http://127.0.0.1:8000/lite/notebooks/index.html?path=my_notebook.ipynb`,
instead of the broken one below
`http://127.0.0.1:8000/lite/retro/notebooks/index.html?path=my_notebook.ipynb`
It appears that this was not caught in other projects, such as `scikit-learn`, because the "Lab" interface is used there, for which the URL is correct here.
I also tried to add a minimal test to ensure that this breakage …

Fix incorrect paths for JupyterLite Notebook interface URLs, unpin `jupyterlite-sphinx`, and update JupyterLite integration docs

---

.pre-commit-config.yaml
doc/configuration.rst
sphinx_gallery/backreferences.py
sphinx_gallery/directives.py
sphinx_gallery/docs_resolv.py
sphinx_gallery/gen_gallery.py
sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_gallery.py
sphinx_gallery/tests/test_utils.py
sphinx_gallery/tests/testconfs/src/plot_1.py
sphinx_gallery/tests/tinybuild/doc/minigallery.rst
sphinx_gallery/utils.py

Follow up to #1430. A few things happening in this PR (sorry!)
**Fixes duplicates between object and file inputs**
In #1430 the dict key used for objects was `Path(target_dir, filename)`, whereas the dict key used for file inputs was `Path(src_dir, filename)`. Thus, files selected via both object and file path would be duplicated.
There were two ways I could have fixed this:
* Change key for file inputs to use `target_dir` - we would have needed to get the `target_dir` anyway to get the thumbnail and it may have been better to raise an error earlier if input path is not in an `examples_dir` (done in `_get_target_dir`) BUT we probably want to sort on `Path(src_dir, filename)` as it's probably easier for users vs `Path(target_dir, filename)`
* Change key for object inputs to use `src_dir` …

Fix minigallery duplicates and add tests and update documenation

---

doc/configuration.rst
sphinx_gallery/gen_gallery.py
sphinx_gallery/tests/test_gen_gallery.py

closes #1411
* Add test for `_bool_eval`
* Adds bool only configurations to `_bool_eval` check
* Improves build options section, as I *think* any configuration can be altered via `-D` build option, as long as it is one of the accepted types by `-D`. As we now accept callables as string path to object, I *think* these can now also be set via `-D`.

MNT Add test for `_bool_eval` and add configs to `_bool_eval` check

---

doc/utils.rst

Running the command as specified gives:
```
/path/to/python: No module named sphinx_gallery_py2jupyter
```

Update instructions for converting script to notebook

---

sphinx_gallery/gen_rst.py

Closes #1489.
I modified the logic for how the sentence inside the note is constructed, specifically:
- The first part of the sentence, as defined in `EXAMPLE_HEADER`, now ends without a period
- Then, if Binder or JupyterLite is being used, the sentence is extended as before, and a period is added at the end of the extended sentence.
- If neither Binder o JypyterLite are used, just a period is added.
I tested my fix by running `make html` from inside `sphinx_gallery/tests/tinybuild/doc` and opening the examples in the generated gallery.
**Before (run in `master` branch):**
**After (run in my branch):**

Fix typo in note about Binder/JupyterLite

---

sphinx_gallery/gen_rst.py
sphinx_gallery/tests/test_full.py
sphinx_gallery/tests/test_gen_rst.py
sphinx_gallery/tests/tinybuild/examples/plot_matplotlib_alt.py

closes #1403
Removes (only) "# noqa: E501" from the end of text blocks:
* it seems that this specific lint qa is the problem, e.g., per #1403 and https://github.com/scikit-learn/scikit-learn/pull/32241#discussion_r2366715332
* a regex to try and remove all 'noqa ...' comments may be a bit brittle
If we get more issues/reports of other qa's being a problem, we can re-open but I thought we could go with YAGNI for now. WDYT @larsoner ?

Remove "# noqa: E501" from end of text blocks
